
#include "definitions.h"

vardefs variable_definition_array[] = {
	{"ambient", "atm_coefs", "_atm_coefs", "matrix_t<double>", "0.006789,0.1046,-0.0170,0.002845;0.01293,0.2748,-.03394,0;0.006789,0.1046,-0.0170,0.002845", "none", "", "FALSE", "", "0.006789,0.1046,-0.0170,0.002845;0.01293,0.2748,-.03394,0;0.006789,0.1046,-0.0170,0.002845", "", "User-defined attenuation", "Atmospheric attenuation coefficients for user-defined analysis"},
	{"ambient", "atm_model", "_atm_model", "int", "0", "none", "[0,3]", "TRUE", "combo", "DELSOL3 clear day=0;DELSOL3 hazy day=1;User-defined=2", "", "Atmospheric attenuation model", "Atmospheric attenuation model {0=25km Barstow, 1 = 5km Barstow, 2 = user defined}"},
	{"ambient", "class_name", "_class_name", "string", "Climate", "none", "", "FALSE", "", "", "", "Class name", "Class name"},
	{"ambient", "date_mday", "_date_time._mday", "double", "_date_time._mday", "day", "[1,31]", "FALSE", "", "", "", "date_mday", "Day of the month setting for date object"},
	{"ambient", "date_month", "_date_time._month", "double", "_date_time._month", "month", "[1,12]", "FALSE", "", "", "", "date_month", "Month setting for date object"},
	{"ambient", "date_wday", "_date_time._wday", "double", "_date_time._wday", "day", "[1,7]", "FALSE", "", "", "", "date_wday", "Day of the week setting for date object"},
	{"ambient", "date_yday", "_date_time._yday", "double", "_date_time._yday", "day", "[1,365]", "FALSE", "", "", "", "date_yday", "Day of the year  setting for date object"},
	{"ambient", "date_year", "_date_time._year", "double", "_date_time._year", "year", "[0.,2150.]", "FALSE", "", "", "", "date_year", "Year setting for date object"},
	{"ambient", "del_h2o", "_del_h2o", "double", "20", "mm H2O", "[0,9e9]", "FALSE", "", "", "", "Atmospheric precipitable water", "Atmospheric precipitable water depth for use in the Allen insolation model"},
	{"ambient", "dni_layout", "_dni_layout", "double", "950", "W/m2", "[0,9999]", "TRUE", "", "", "", "Constant DNI for layout calculations", "DNI to use during all layout calculations. CONSTANT model only."},
	{"ambient", "dpres", "_dpres", "double", "1", "atm", "[0,2]", "TRUE", "", "", "", "Ambient pressure", "Local ambient pressure relative to sea-level pressure"},
	{"ambient", "elevation", "_elevation", "double", "588", "m", "[-424.,8850.]", "FALSE", "", "", "", "Plant elevation", "Plant mean elevation"},
	{"ambient", "insol_type", "_insol_type", "int", "-1", "none", "[-1,4]", "FALSE", "combo", "Weather file data=-1;Meinel model=0;Hottel model=1;Constant value=2;Allen model=3;Moon model=4", "", "Insolation model", "Model used to determine insolation as a function of time"},
	{"ambient", "latitude", "_latitude", "double", "34.867", "deg", "[-90.,90.]", "FALSE", "", "", "", "Plant latitude", "Plant latitude"},
	{"ambient", "longitude", "_longitude", "double", "-116.783", "deg", "[-180.,180.]", "FALSE", "", "", "", "Plant longitude", "Plant longitude"},
	{"ambient", "sun_azimuth", "_azimuth", "double", "0", "deg", "[-180.,180.]", "FALSE", "", "", "", "sun_azimuth", "User-set solar azimuth angle"},
	{"ambient", "sun_csr", "_sun_csr", "double", "0.1", "none", "[0,1)", "TRUE", "", "", "", "Circumsolar ratio", "Ratio of solar flux contained in the circumsolar ring over the solar disc flux"},
	{"ambient", "sun_pos_map", "_sun_pos", "matrix_t<double>", "", "[deg,deg]", "", "FALSE", "", "", "", "sun_pos_map", "Map of sun positions to use for calculations"},
	{"ambient", "sun_rad_limit", "_sun_rad_limit", "double", "4.65", "mrad", "(0,1000]", "TRUE", "", "", "", "Sunshape angular extent", "Half-angle of sunshape size (4.65mrad for Pillbox, 2.73mrad for Gaussian)"},
	{"ambient", "sun_type", "_suntype", "int", "1", "none", "[0,3]", "TRUE", "combo", "Pillbox sun=2;Gaussian sun=4;Limb-darkened sun=1;Point sun=0;Buie CSR=5;User sun=3;", "", "Sunshape model", "Sunshape model - {0=point sun, 1=limb darkened sun, 2=square wave sun, 3=user sun}"},
	{"ambient", "sun_zenith", "_zenith", "double", "0.5", "deg", "[0.,90]", "FALSE", "", "", "", "sun_zenith", "User-set solar zenith angle"},
	{"ambient", "time_hour", "_date_time._hour", "double", "_date_time._hour", "hr", "[0,24)", "FALSE", "", "", "", "time_hour", "Hour of the day setting for date object"},
	{"ambient", "time_min", "_date_time._min", "double", "_date_time._min", "min", "[0,60)", "FALSE", "", "", "", "time_min", "Minute of the hour setting for date object"},
	{"ambient", "time_ms", "_date_time._ms", "double", "_date_time._ms", "ms", "[0,1000)", "FALSE", "", "", "", "time_ms", "Millisecond of the second setting for date object"},
	{"ambient", "time_sec", "_date_time._sec", "double", "_date_time._sec", "sec", "[0,60)", "FALSE", "", "", "", "time_sec", "Second of the minute setting for date object"},
	{"ambient", "time_zone", "_time_zone", "double", "-8", "hr", "[-12,12]", "FALSE", "", "", "", "Time zone", "Time zone"},
	{"ambient", "user_sun", "_user_sun", "matrix_t<double>", "", "[deg,deg]", "", "FALSE", "", "", "", "user_sun", "Array of intensity at various angles from the centroid of the sun"},
	{"ambient", "weather_file", "_weather_file", "string", "CA Daggett.tm2", "none", "", "TRUE", "", "", "", "Weather file", "Weather file to use for analysis"},
	{"ambient", "wf_data", "_wf_data", "WeatherData", "", "none", "", "FALSE", "", "", "", "wf_data", "Data entries in the weather file"},
	{"ambient", "wf_type", "_wf_type", "string", "TM2", "none", "", "FALSE", "", "", "", "wf_type", "weather file type {TM2, TM3, SMW, EPW, USER}"},
	{"financial", "class_name", "_class_name", "string", "Financial", "none", "", "FALSE", "", "", "", "Class name", "Class name"},
	{"financial", "contingency_cost", "_contingency_cost", "double", "0", "$", "", "FALSE", "", "", "", "Contingency cost", "Contingency cost"},
	{"financial", "contingency_rate", "_contingency_rate", "double", "7", "%", "", "TRUE", "", "", "", "Contingency", "Fraction of the direct capital costs added to account for contingency"},
	{"financial", "cost_per_capacity", "_cost_per_capacity", "double", "0", "$/kWe", "", "FALSE", "", "", "", "Estimated cost per capacity (net)", "Estimated capital cost per capacity (net)"},
	{"financial", "fixed_cost", "_fixed_cost", "double", "0", "$", "", "FALSE", "", "", "", "Fixed cost", "Cost that does not scale with any plant parameter"},
	{"financial", "heliostat_cost", "_heliostat_cost", "double", "0", "$", "", "FALSE", "", "", "", "Heliostat field cost", "Heliostat field cost"},
	{"financial", "heliostat_spec_cost", "_heliostat_spec_cost", "double", "180", "$/m2", "[-9e9,9e9]", "TRUE", "", "", "", "Heliostat field", "Cost per square meter of heliostat aperture area of the heliostat field"},
	{"financial", "is_pmt_factors", "_is_pmt_factors", "bool", "FALSE", "", "", "FALSE", "checkbox", "", "", "Enable payment weighting factors", "Enable or disable the use of weighting factors in determining field layout"},
	{"financial", "land_cost", "_land_cost", "double", "0", "$", "", "FALSE", "", "", "", "Land cost", "Land cost"},
	{"financial", "land_const", "_land_const", "double", "45", "acre", "", "TRUE", "", "", "", "Non-solar field land area", "Fixed land area that is added to the area occupied by heliostats"},
	{"financial", "land_mult", "_land_mult", "double", "1.3", "none", "", "TRUE", "", "", "", "Solar field land area multiplier", "Factor multiplying the land area occupied by heliostats"},
	{"financial", "land_area_tot", "_land_area_tot", "double", "0", "acre", "", "FALSE", "", "", "", "Total land area", "Total calculated land area"},
	{"financial", "land_spec_cost", "_land_spec_cost", "double", "10000", "$/acre", "", "TRUE", "", "", "", "Land cost per acre", "Cost of land per acre including the footprint of the land occupied by the entire plant."},
	{"financial", "plant_cost", "_plant_cost", "double", "0", "$", "", "FALSE", "", "", "", "Power block and plant cost", "Cost of the power block and balance of plant equipment"},
	{"financial", "plant_spec_cost", "_plant_spec_cost", "double", "1200", "$/kWe", "", "TRUE", "", "", "", "Power block and plant ", "Cost of the power block and balance of plant equipment per kilowatt (electric) gross design power"},
	{"financial", "pmt_factor_1", "_pmt_factor_1", "double", "2.064", "none", "", "FALSE", "", "", "", "Payment allocation - period 1", "Relative value of electricity produced during this period compared to the average"},
	{"financial", "pmt_factor_2", "_pmt_factor_2", "double", "1.2", "none", "", "FALSE", "", "", "", "Payment allocation - period 2", "Relative value of electricity produced during this period compared to the average"},
	{"financial", "pmt_factor_3", "_pmt_factor_3", "double", "1", "none", "", "FALSE", "", "", "", "Payment allocation - period 3", "Relative value of electricity produced during this period compared to the average"},
	{"financial", "pmt_factor_4", "_pmt_factor_4", "double", "1.1", "none", "", "FALSE", "", "", "", "Payment allocation - period 4", "Relative value of electricity produced during this period compared to the average"},
	{"financial", "pmt_factor_5", "_pmt_factor_5", "double", "0.8", "none", "", "FALSE", "", "", "", "Payment allocation - period 5", "Relative value of electricity produced during this period compared to the average"},
	{"financial", "pmt_factor_6", "_pmt_factor_6", "double", "0.7", "none", "", "FALSE", "", "", "", "Payment allocation - period 6", "Relative value of electricity produced during this period compared to the average"},
	{"financial", "pmt_factor_7", "_pmt_factor_7", "double", "1", "none", "", "FALSE", "", "", "", "Payment allocation - period 7", "Relative value of electricity produced during this period compared to the average"},
	{"financial", "pmt_factor_8", "_pmt_factor_8", "double", "1", "none", "", "FALSE", "", "", "", "Payment allocation - period 8", "Relative value of electricity produced during this period compared to the average"},
	{"financial", "pmt_factor_9", "_pmt_factor_9", "double", "1", "none", "", "FALSE", "", "", "", "Payment allocation - period 9", "Relative value of electricity produced during this period compared to the average"},
	{"financial", "rec_cost", "_rec_cost", "double", "84944751.6", "$", "", "FALSE", "", "", "", "Receiver cost", "Receiver cost"},
	{"financial", "rec_cost_exp", "_rec_cost_exp", "double", "0.7", "none", "[-9e9,9e9]", "TRUE", "", "", "", "Receiver cost scaling exponent", "Exponent in the equation (total cost) = (ref. cost) * ( (area) / (ref. area) ) ^ X"},
	{"financial", "rec_ref_area", "_rec_ref_area", "double", "1571", "m2", "", "TRUE", "", "", "", "Receiver reference area", "Receiver surface area corresponding to the receiver reference cost"},
	{"financial", "rec_ref_cost", "_rec_ref_cost", "double", "126200000", "$", "[-9e9,9e9]", "TRUE", "", "", "", "Receiver reference cost", "Cost of the receiver at the sizing indicated by the reference receiver area"},
	{"financial", "sales_tax_cost", "_sales_tax_cost", "double", "0", "$", "", "TRUE", "", "", "", "Sales tax cost", "Sales tax cost"},
	{"financial", "sales_tax_frac", "_sales_tax_frac", "double", "80", "%", "", "TRUE", "", "", "", "Sales tax rate portion", "Fraction of the direct capital costs for which sales tax applies"},
	{"financial", "sales_tax_rate", "_sales_tax_rate", "double", "5", "%", "", "TRUE", "", "", "", "Sales tax rate", "Sales tax rate applid to the total direct capital cost"},
	{"financial", "site_cost", "_site_cost", "double", "0", "$", "", "FALSE", "", "", "", "Site improvements cost", "Site improvements cost"},
	{"financial", "site_spec_cost", "_site_spec_cost", "double", "20", "$/m2", "[-9e9,9e9]", "TRUE", "", "", "", "Site improvements", "Cost per square meter of heliostat aperture area of site improvements"},
	{"financial", "tes_cost", "_tes_cost", "double", "0", "$", "", "FALSE", "", "", "", "Thermal storage cost", "Thermal storage cost"},
	{"financial", "tes_spec_cost", "_tes_spec_cost", "double", "27", "$/kWht", "", "TRUE", "", "", "", "Thermal storage", "Cost of thermal storage per kilowatt hour (thermal) capacity"},
	{"financial", "total_direct_cost", "_total_direct_cost", "double", "0", "$", "", "FALSE", "", "", "", "Total direct cost", "Sum of all direct costs"},
	{"financial", "total_indirect_cost", "_total_indirect_cost", "double", "0", "$", "", "FALSE", "", "", "", "Total indirect cost", "Sum of all indirect costs"},
	{"financial", "total_installed_cost", "_total_installed_cost", "double", "0", "$", "", "FALSE", "", "", "", "Total installed cost", "Sum of direct and indirect costs"},
	{"financial", "tower_cost", "_tower_cost", "double", "14736146", "$", "", "FALSE", "", "", "", "Tower cost", "Tower cost"},
	{"financial", "tower_exp", "_tower_exp", "double", "0.0113", "none", "[-9e9,9e9]", "TRUE", "", "", "", "Tower cost scaling exponent", "Exponent in the equation (total cost) = (fixed cost) * exp( X * (tower height) )"},
	{"financial", "tower_fixed_cost", "_tower_fixed_cost", "double", "1927000", "$", "[0,9e9]", "TRUE", "", "", "", "Fixed tower cost", "Fixed tower cost - used as the basis for scaling tower cost as a function of height"},
	{"financial", "weekday_sched", "_weekday_sched", "string", "666666554444444444444555666666554444444444444555666666554444444444444555666666554444444444444555666666554444444444444555333333332222111111222333333333332222111111222333333333332222111111222333333333332222111111222333666666554444444444444555666666554444444444444555666666554444444444444555", "", "", "FALSE", "", "", "", "Weekday dispatch period schedule", "Weekday dispatch period schedule"},
	{"financial", "weekend_sched", "_weekend_sched", "string", "666666555555555555555555666666555555555555555555666666555555555555555555666666555555555555555555666666555555555555555555333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333666666555555555555555555666666555555555555555555666666555555555555555555", "", "", "FALSE", "", "", "", "Weekend dispatch period schedule", "Weekend dispatch period schedule"},
	{"financial", "wiring_cost", "_wiring_cost", "double", "0", "$", "", "FALSE", "", "", "", "Wiring cost", "Wiring cost"},
	{"financial", "wiring_user_spec", "_wiring_user_spec", "double", "9", "$/m2", "[-9e9,9e9]", "TRUE", "", "", "", "Wiring specific cost", "Cost of wiring per square meter of heliostat aperture area"},
	{"fluxsim", "aim_method", "_aim_method", "int", "3", "", "", "TRUE", "combo", "Simple aim points=0;Sigma aiming=1;Probability shift=2;Image size priority=3;Keep existing=4", "", "Heliostat aim point method", "Method for determining the aim point for each heliostat"},
	{"fluxsim", "class_name", "_class_name", "string", "Performance Simulation", "none", "", "FALSE", "", "", "", "Class name", "Class name"},
	{"fluxsim", "cloud_depth", "_cloud_depth", "double", "250", "m", "", "TRUE", "", "", "", "Cloud depth", "Depth of the cloud shape"},
	{"fluxsim", "cloud_loc_x", "_cloud_loc_x", "double", "200", "m", "", "TRUE", "", "", "", "Cloud location (X)", "Base location of the cloud(s) relative to the tower position - X dimension"},
	{"fluxsim", "cloud_loc_y", "_cloud_loc_y", "double", "200", "m", "", "TRUE", "", "", "", "Cloud location (Y)", "Base location of the cloud(s) relative to the tower position - Y dimension"},
	{"fluxsim", "cloud_opacity", "_cloud_opacity", "double", "0.8", "none", "[0,1]", "TRUE", "", "", "", "Cloud opacity", "Fraction of DNI obfuscated by a cloud shadow"},
	{"fluxsim", "cloud_sep_depth", "_cloud_sep_depth", "double", "1", "", "", "TRUE", "", "", "", "Cloud pattern depth spacing mult.", "Cloud pattern depth spacing"},
	{"fluxsim", "cloud_sep_width", "_cloud_sep_width", "double", "2", "", "", "TRUE", "", "", "", "Cloud pattern width spacing mult.", "Cloud pattern width spacing"},
	{"fluxsim", "cloud_shape", "_cloud_shape", "int", "0", "", "", "TRUE", "combo", "Elliptical=0;Rectangular=1;Front=2", "", "Cloud shape", "Shape used to model the cloud shadow"},
	{"fluxsim", "cloud_skew", "_cloud_skew", "double", "35", "deg", "[-180,180]", "TRUE", "", "", "", "Cloud orientation angle", "Angle between North and the depth direction (-180 to +180 with clockwise positive)"},
	{"fluxsim", "cloud_width", "_cloud_width", "double", "500", "m", "", "TRUE", "", "", "", "Cloud width", "Width of the cloud shape"},
	{"fluxsim", "flux_day", "_flux_day", "int", "20", "", "[1,31]", "TRUE", "", "", "", "Day of the month", "Day of the month for the flux simulation"},
	{"fluxsim", "flux_dist", "_flux_dist", "int", "0", "", "", "TRUE", "combo", "Triangular=0;Normal=1;Uniform=2", "", "Aim point distribution sampling", "Sampling basis for random positioning. Non-uniform distributions are weighted away from the center."},
	{"fluxsim", "flux_hour", "_flux_hour", "double", "12", "hr", "[0,24)", "TRUE", "", "", "", "Hour of the day", "Hour of the day for the flux simulation"},
	{"fluxsim", "flux_model", "_flux_model", "int", "0", "none", "", "FALSE", "combo", "Hermite (analytical)=0;SolTrace=1", "", "Flux simulation model", "Desired flux simulation tool. Not all geometries can be simulated using the Hermite approximation."},
	{"fluxsim", "flux_month", "_flux_month", "int", "3", "", "[1,12]", "TRUE", "", "", "", "Month of the year", "Month of the year for the flux simulation"},
	{"fluxsim", "flux_solar_az", "_flux_solar_az", "double", "180", "deg", "", "FALSE", "", "", "", "Calculated solar azimuth angle", "Solar azimuth angle to use for the flux simulation"},
	{"fluxsim", "flux_solar_az_in", "_flux_solar_az_in", "double", "180", "", "[-180,180]", "TRUE", "", "", "", "Solar azimuth angle (0=N)", "Solar azimuth angle to use for the flux simulation"},
	{"fluxsim", "flux_solar_el", "_flux_solar_el", "double", "85", "deg", "", "FALSE", "", "", "", "Calculated solar elevation angle", "Solar elevation angle to use for the flux simulation"},
	{"fluxsim", "flux_solar_el_in", "_flux_solar_el_in", "double", "85", "", "[0,90]", "TRUE", "", "", "", "Solar elevation angle", "Solar elevation angle to use for the flux simulation"},
	{"fluxsim", "flux_time_type", "_flux_time_type", "int", "1", "none", "", "FALSE", "combo", "Sun position=0;Hour/Day=1", "", "Simulation time spec. method", "Method for specifying the desired flux simulation time."},
	{"fluxsim", "is_cloud_pattern", "_is_cloud_pattern", "bool", "TRUE", "", "", "TRUE", "checkbox", "", "", "Enable cloud pattern", "Create a pattern based on the specified cloud"},
	{"fluxsim", "is_cloud_symd", "_is_cloud_symd", "bool", "TRUE", "", "", "TRUE", "checkbox", "", "", "Pattern symmetric in depth direction", "Mirror the cloud pattern below the width axis"},
	{"fluxsim", "is_cloud_symw", "_is_cloud_symw", "bool", "TRUE", "", "", "TRUE", "checkbox", "", "", "Pattern symmetric in width direction", "Mirror the cloud pattern to the left of the depth axis"},
	{"fluxsim", "is_cloudy", "_is_cloudy", "bool", "FALSE", "", "", "TRUE", "checkbox", "", "", "Simulate cloud transient", "Enable simulation for a cloud transient"},
	{"fluxsim", "is_optical_err", "_is_optical_err", "bool", "TRUE", "", "", "FALSE", "checkbox", "", "", "Include optical errors", "Include the reflector optical error sources in the SolTrace simulation"},
	{"fluxsim", "is_sunshape_err", "_is_sunshape_err", "bool", "TRUE", "", "", "FALSE", "checkbox", "", "", "Include sun shape", "Include the sun shape error in the SolTrace simulation"},
	{"fluxsim", "max_rays", "_max_rays", "int", "1000000", "none", "[1,1e99]", "FALSE", "", "", "", "Maximum number of generated rays", "The maximum number of generated rays allowed before terminating the simulation. Overrides the desired rays setting."},
	{"fluxsim", "min_rays", "_min_rays", "int", "10000", "none", "[1,1e99]", "FALSE", "", "", "", "Desired number of ray intersections", "The minimum number of ray hits on the receiver before terminating the simulation."},
	{"fluxsim", "norm_dist_sigma", "_norm_dist_sigma", "double", "0.25", "", "(0.,1.]", "TRUE", "", "", "", "Aiming distribution standard dev.", "Size of the standard distribution relative to half of the height of the receiver."},
	{"fluxsim", "save_data", "_save_data", "bool", "FALSE", "", "", "FALSE", "checkbox", "", "", "Save raytrace data", "Save the results for each ray"},
	{"fluxsim", "save_data_loc", "_save_data_loc", "string", "soltrace_ray_data.csv", "", "", "FALSE", "", "", "", "ray data", "Choose a location to save the ray data"},
	{"fluxsim", "seed", "_seed", "int", "-1", "none", "[-1, 9e9]", "FALSE", "", "", "", "Seed value (-1 for automatic selection)", "The seed for the random number generator"},
	{"fluxsim", "sigma_limit", "_sigma_limit", "double", "2", "", "[0.,1000]", "TRUE", "", "", "", "Positioning cutoff (standard deviations)", "Image positioning cutoff - desired distance of each image in standard deviations from the receiver edge"},
	{"fluxsim", "x_res", "_x_res", "int", "25", "none", "[1,1000]", "FALSE", "", "", "", "Flux grid resolution - Horizontal", "Number of flux test points per panel (maximum) in the vertical direction for the flux simulation"},
	{"fluxsim", "y_res", "_y_res", "int", "25", "none", "[1,1000]", "FALSE", "", "", "", "Flux grid resolution - Vertical", "Number of flux test points per panel (maximum) in the horizontal direction for the flux simulation"},
	{"heliostat", "a_total", "_a_total", "double", "0", "m2", "", "FALSE", "", "", "", "Total reflective aperture area", "Aperture area including geometry penalties and gaps in the structure"},
	{"heliostat", "cant_day", "_dcant", "double", "82", "day", "[1,365]", "TRUE", "", "", "", "Canting day of the year", "Day of the year used for canting the heliostats (1-365)"},
	{"heliostat", "cant_hour", "_hcant", "double", "0", "hr", "(-12.,12.]", "TRUE", "", "", "", "Canting hour (past noon)", "Hours past noon at which the mirror panels are canted (-12 to 12)"},
	{"heliostat", "cant_mag_i", "_cant_mag_i", "double", "0", "none", "", "FALSE", "", "", "", "Total canting vector - i", "Total canting vector - i"},
	{"heliostat", "cant_mag_j", "_cant_mag_j", "double", "0", "none", "", "FALSE", "", "", "", "Total canting vector - j", "Total canting vector - j"},
	{"heliostat", "cant_mag_k", "_cant_mag_k", "double", "0", "none", "", "FALSE", "", "", "", "Total canting vector - k", "Total canting vector - k"},
	{"heliostat", "cant_method", "_cant_method", "int", "-1", "none", "[-1,3]", "TRUE", "combo", "No canting=0;On-axis at slant=-1;On-axis, user-defined=1;Off-axis, day and hour=3; User-defined vector=4", "", "Heliostat canting method", "Integer to specify the canting method {0=none, -1=Cant on-axis equal to slant range, 1=user-defined on-axis, 3=user-defined off-axis at hour + day}"},
	{"heliostat", "cant_norm_i", "_cant_norm_i", "double", "0", "none", "", "FALSE", "", "", "", "Normalized canting vector - i", "Normalized canting vector - i"},
	{"heliostat", "cant_norm_j", "_cant_norm_j", "double", "0", "none", "", "FALSE", "", "", "", "Normalized canting vector - j", "Normalized canting vector - j"},
	{"heliostat", "cant_norm_k", "_cant_norm_k", "double", "0", "none", "", "FALSE", "", "", "", "Normalized canting vector - k", "Normalized canting vector - k"},
	{"heliostat", "cant_rad_scaled", "_rcant_scaled", "double", "6", "none", "[-9e9,9e9]", "TRUE", "", "", "", "Canting radius factor", "Canting radius value (absolute value if radius is not scaled, multiplied by tower height if scaled)"},
	{"heliostat", "cant_radius", "_rcant", "double", "1000", "m", "(0.,9e99]", "FALSE", "", "", "", "Canting radius", "Radius for canting focal point assuming on-axis canting"},
	{"heliostat", "cant_sun_az", "_cant_sun_az", "double", "0", "deg", "", "FALSE", "", "", "", "Sun azimuth at canting", "Sun azimuth angle at the moment the cant panels are focused on the receiver"},
	{"heliostat", "cant_sun_el", "_cant_sun_el", "double", "0", "deg", "", "FALSE", "", "", "", "Sun elevation at canting", "Sun elevation angle at the moment the cant panels are focused on the receiver"},
	{"heliostat", "cant_vect_i", "_cant_vect.i", "double", "0", "none", "[-9e9,9e9]", "TRUE", "", "", "", "Canting vector x-component", "Canting vector - x-component"},
	{"heliostat", "cant_vect_j", "_cant_vect.j", "double", "0", "none", "[-9e9,9e9]", "TRUE", "", "", "", "Canting vector y-component", "Canting vector y-component"},
	{"heliostat", "cant_vect_k", "_cant_vect.k", "double", "1", "none", "[-9e9,9e9]", "TRUE", "", "", "", "Canting vector z-component", "Canting vector z-component"},
	{"heliostat", "cant_vect_scale", "_cant_vect_scale", "double", "400", "m", "[-9e9,9e9]", "TRUE", "", "", "", "Canting vector magnitude", "Value to scale the canting unit vector to determine actual canting magnitude"},
	{"heliostat", "class_name", "_class_name", "string", "Heliostat", "none", "", "FALSE", "", "", "", "Class name", "Class name"},
	{"heliostat", "diameter", "_dm", "double", "13.77", "m", "(0.,1000.]", "TRUE", "", "", "", "Heliostat diameter", "Diameter of the heliostat structure (round heliostats only)"},
	{"heliostat", "err_azimuth", "_sigaz", "double", "0", "rad", "[0.,1000.]", "TRUE", "", "", "", "Azimuth pointing error", "Standard deviation of the normal error dist. of the azimuth angle"},
	{"heliostat", "err_elevation", "_sigel", "double", "0", "rad", "[0.,1000.]", "TRUE", "", "", "", "Elevation pointing error", "Standard deviation of the normal error dist. of the elevation angle"},
	{"heliostat", "err_reflect_x", "_sigtx", "double", "0.0002", "rad", "[0.,1000.]", "TRUE", "", "", "", "Reflected beam error in X", "error in reflected vector (horiz.) caused by atmospheric refraction, tower sway, etc."},
	{"heliostat", "err_reflect_y", "_sigty", "double", "0.0002", "rad", "[0.,1000.]", "TRUE", "", "", "", "Reflected beam error in Y", "error in reflected vector (vert.) caused by atmospheric refraction, tower sway, etc."},
	{"heliostat", "err_surface_x", "_sigsx", "double", "0.00153", "rad", "[0.,1000.]", "TRUE", "", "", "", "Surface slope error in X", "Std.dev. of the normal error dist. of the reflective surface normal in the X (horizontal)"},
	{"heliostat", "err_surface_y", "_sigsy", "double", "0.00153", "rad", "[0.,1000.]", "TRUE", "", "", "", "Surface slope error in Y", "Same as above, but in the vertical direction"},
	{"heliostat", "err_total", "_err_total", "double", "0", "rad", "", "FALSE", "", "", "", "Total reflected image error", "Total convolved optical error in the reflected beam from the above sources"},
	{"heliostat", "focus_method", "_focus_method", "int", "1", "none", "[0,3]", "TRUE", "combo", "Flat=0;At slant=1;Group average=2;User-defined=3", "", "Heliostat focusing type", "The focusing method {0=Flat, 1=Each at slant, 2=Average of group, 3=User defined}"},
	{"heliostat", "height", "_hm", "double", "12.2", "m", "(0.,1000.]", "TRUE", "", "", "", "Structure height", "Height of the heliostat structure"},
	{"heliostat", "helio_name", "_helio_name", "string", "Template 1", "", "", "FALSE", "", "", "", "Heliostat template name", "Heliostat template name"},
	{"heliostat", "id", "_id", "int", "-1", "none", "[-1,9e99]", "FALSE", "", "", "", "id", "Unique ID number for the heliostat template"},
	{"heliostat", "is_cant_rad_scaled", "_is_cant_rad_scaled", "bool", "TRUE", "", "", "FALSE", "checkbox", "", "", "Scale cant radius with tower height", "The cant radius scales with tower height"},
	{"heliostat", "is_cant_vect_slant", "_is_cant_vect_slant", "bool", "FALSE", "none", "", "FALSE", "checkbox", "", "", "Scale vector with slant range", "Multiply the canting vector by the slant range"},
	{"heliostat", "is_enabled", "_is_enabled", "bool", "TRUE", "", "", "FALSE", "", "", "", "Is template enabled?", "Is template enabled?"},
	{"heliostat", "is_faceted", "_is_faceted", "bool", "TRUE", "none", "", "FALSE", "checkbox", "", "", "Use multiple panels", "The number of reflective panels per heliostat is greater than 1"},
	{"heliostat", "is_focal_equal", "_is_focal_equal", "bool", "TRUE", "none", "", "FALSE", "checkbox", "", "", "Use single focal length", "Both the X and Y focal lengths will use a single value as indicated by the X focal length"},
	{"heliostat", "is_round", "_is_round", "bool", "0", "none", " ", "FALSE", "combo", "Rectangular=0;Round=1", "", "Heliostat shape", "Is the heliostat round (true) or rectangular (false)"},
	{"heliostat", "is_xfocus", "_is_xfocus", "bool", "TRUE", "none", " ", "FALSE", "checkbox", "", "", "Focus in X", "Reflector is focused in with respect to the heliostat X axis"},
	{"heliostat", "is_yfocus", "_is_yfocus", "bool", "TRUE", "none", " ", "FALSE", "checkbox", "", "", "Focus in Y", "Reflector is focused in with respect to the heliostat Y axis"},
	{"heliostat", "location_x", "_location.x", "double", "0", "m", "[-9e9,9e9]", "FALSE", "", "", "", "location_x", "X Location of heliostat in the field (0,0,Zt) is the location of the tower base"},
	{"heliostat", "location_y", "_location.y", "double", "0", "m", "[-9e9,9e9]", "FALSE", "", "", "", "location_y", "Y Location of heliostat in the field (0,0,Zt) is the location of the tower base"},
	{"heliostat", "location_z", "_location.z", "double", "0", "m", "[-9e9,9e9]", "FALSE", "", "", "", "location_z", "Z Location of heliostat in the field (0,0,Zt) is the location of the tower base"},
	{"heliostat", "n_cant_x", "_ncantx", "int", "2", "", "[1,1000]", "TRUE", "", "", "", "No. horizontal panels", "Number of cant panels in the X direction"},
	{"heliostat", "n_cant_y", "_ncanty", "int", "8", "", "[1,1000]", "TRUE", "", "", "", "No. vertical panels", "Number of cant panels in the Y direction"},
	{"heliostat", "n_rot_axes", "_nrotax", "int", "2", "", "[0,2]", "FALSE", "", "", "", "n_rot_axes", "Number of rotational axes on the tracker (1 for LFresnel, 2 for heliostat)"},
	{"heliostat", "r_collision", "_rcoll", "double", "0", "m", "(0.,1000.]", "FALSE", "", "", "", "Heliostat footprint diameter", "Heliostat reflector maximum footprint diameter"},
	{"heliostat", "ref_total", "_ref_total", "double", "0", "none", "", "FALSE", "", "", "", "Total optical reflectance", "Effective reflectance - product of the mirror reflectance and soiling"},
	{"heliostat", "reflect_ratio", "_densmr", "double", "0.97", "none", "(0.,1.]", "TRUE", "", "", "", "Reflective surface ratio", "Ratio of mirror area to total area of the heliostat defined by wm x hm"},
	{"heliostat", "reflectivity", "eff_data.reflectivity", "double", "0.95", "none", "(0.,1.]", "TRUE", "", "", "", "Mirror reflectivity", "Average reflectivity (clean) of the mirrored surface"},
	{"heliostat", "rvel_max_x", "_maxrvelx", "double", "1000", "rad/s", "(0.,9e99]", "FALSE", "", "", "", "rvel_max_x", "maximum rotational velocity about the x axis"},
	{"heliostat", "rvel_max_y", "_maxrvelz", "double", "1000", "rad/s", "(0.,9e99]", "FALSE", "", "", "", "rvel_max_y", "maximum rotational velocity about the z axis"},
	{"heliostat", "soiling", "eff_data.soiling", "double", "0.95", "none", "[0.,1.]", "TRUE", "", "", "", "Soiling factor", "Average soiling factor"},
	{"heliostat", "temp_az_max", "_temp_az_max", "double", "360", "deg", "[-180.,180]", "FALSE", "", "", "", "Max. angular boundary for heliostat type", "Angular boundary for heliostat geometry - on the clockwise side of the region"},
	{"heliostat", "temp_az_min", "_temp_az_min", "double", "0", "deg", "[-180.,180]", "FALSE", "", "", "", "Min. angular boundary for heliostat type", "Angular boundary for heliostat geometry - on the counter-clockwise side of the region"},
	{"heliostat", "temp_rad_max", "_temp_rad_max", "double", "7.5", "none", "[0,9e9]", "FALSE", "", "", "", "Maximum radius for heliostat type", "Maximum radius at which this heliostat geometry can be used"},
	{"heliostat", "temp_rad_min", "_temp_rad_min", "double", "0.75", "none", "[0,9e9]", "FALSE", "", "", "", "Minimum radius for heliostat type", "Minimum radius at which this heliostat geometry can be used"},
	{"heliostat", "type", "_type", "int", "0", "", "[0,9e9]", "FALSE", "", "", "", "type", "Integer used to group heliostats into geometries within a field, (e.g. 5 different focal length designs)"},
	{"heliostat", "width", "_wm", "double", "12.2", "m", "(0.,1000.]", "TRUE", "", "", "", "Structure width", "Width of the heliostat structure"},
	{"heliostat", "x_focal_length", "_xfocal", "double", "1000", "m", "(0.,9e99]", "TRUE", "", "", "", "Focal length in X", "Reflector focal length with respect to the heliostat X (horizontal) axis"},
	{"heliostat", "x_gap", "_wgap", "double", "0", "m", "[0.,1000.]", "TRUE", "", "", "", "Cant panel horiz. gap", "Separation between panels in the horizontal direction"},
	{"heliostat", "y_focal_length", "_yfocal", "double", "1000", "m", "(0.,9e99]", "TRUE", "", "", "", "Focal length in Y", "Reflector focal length with respect to the heliostat Y (vertical) axis"},
	{"heliostat", "y_gap", "_hgap", "double", "0", "m", "[0.,1000.]", "TRUE", "", "", "", "Cant panel vert. gap", "Separation between panels in the vertical direction"},
	{"land", "class_name", "_class_name", "string", "Land", "none", "", "FALSE", "", "", "", "Class name", "Class name"},
	{"land", "exclusions", "_exclusions", "vector<vector<Point>>", "", "", "", "FALSE", "", "", "", "exclusions", "Vector of arrays that specify the regions of land to exclude in the heliostat layout"},
	{"land", "import_tower_lat", "_import_tower_lat", "double", "0", "deg", "[-180,180]", "FALSE", "", "", "", "Imported land boundary tower latitude", "Imported land boundary tower latitude"},
	{"land", "import_tower_lon", "_import_tower_lon", "double", "0", "deg", "[-90,90]", "FALSE", "", "", "", "Imported land boundary tower longitude", "Imported land boundary tower longitude"},
	{"land", "import_tower_set", "_import_tower_set", "bool", "FALSE", "none", "", "FALSE", "", "", "", "Imported land boundary tower flag", "Has the tower location been set for imported land geometries?"},
	{"land", "inclusions", "_inclusions", "vector<vector<Point>>", "", "", "", "FALSE", "", "", "", "inclusions", "Vector of arrays that specify the regions of land to include in the heliostat layout"},
	{"land", "is_bounds_array", "_is_bounds_array", "bool", "FALSE", "none", "", "FALSE", "checkbox", "", "", "Use land boundary array", "Land boundary is specified by points array"},
	{"land", "is_bounds_fixed", "_is_bounds_fixed", "bool", "FALSE", "none", "", "FALSE", "checkbox", "", "", "Use fixed land bounds", "Land boundary has fixed limits (not more than | not less than)"},
	{"land", "is_bounds_scaled", "_is_bounds_scaled", "bool", "TRUE", "none", "", "FALSE", "checkbox", "", "", "Bounds scale with tower height", "Land boundary scales with tower hight value"},
	{"land", "is_land_max_opt", "_is_land_max_opt", "bool", "TRUE", "", "", "FALSE", "checkbox", "", "", "Optimize outer land boundary", "Optimize outer land boundary"},
	{"land", "is_land_max_restrict", "_is_land_max_restrict", "bool", "FALSE", "", "", "FALSE", "checkbox", "", "X", "Restrict outer land boundary range", "Restrict outer land boundary range"},
	{"land", "land_max_opt_max", "_land_max_opt_max", "double", "6", "tower-ht", "[1,20]", "FALSE", "", "", "X", "Maximum outer boundary value", "Maximum outer boundary value"},
	{"land", "land_max_opt_min", "_land_max_opt_min", "double", "23", "tower-ht", "[1,20]", "FALSE", "", "", "X", "Minimum outer boundary value", "Minimum outer boundary value"},
	{"land", "max_fixed_rad", "_max_fixed_rad", "double", "1500", "m", "(0.,9e99]", "TRUE", "", "", "", "Maximum land radius (fixed)", "Outer land boundary for circular land plot"},
	{"land", "max_scaled_rad", "_max_scaled_rad", "double", "7.5", "none", "(0.,100.]", "TRUE", "", "", "", "Maximum field radius", "Maximum radius (in units of tower height) for positioning of the heliostats"},
	{"land", "min_fixed_rad", "_min_fixed_rad", "double", "100", "m", "(0.,9e99]", "TRUE", "", "", "", "Minimum land radius (fixed)", "Inner land boundary for circular land plot"},
	{"land", "min_scaled_rad", "_min_scaled_rad", "double", "0.75", "none", "[0.,100.]", "TRUE", "", "", "", "Minimum field radius", "Minimum radius (in units of tower height) for positioning of the heliostats"},
	{"land", "topo_grid", "_topo_grid", "vector<Point>", "", "m", "", "FALSE", "", "", "", "topo_grid", "Regular grid of the land topology of the solar field"},
	{"land", "bound_area", "bound_area", "double", "0", "acre", "", "FALSE", "", "", "", "Solar field land area", "Land area occupied by heliostats. This value is the area of a convex hull surrounding the heliostat positions."},
	{"optimize", "aspect_display", "_aspect_display", "double", "", "none", "", "FALSE", "", "", "", "Current receiver aspect ratio (H/W)", "Current receiver aspect ratio (H/W)"},
	{"optimize", "converge_tol", "_converge_tol", "double", "0.001", "none", "", "FALSE", "", "", "", "Convergence tolerance", "Relative change in the objective function below which convergence is achieved"},
	{"optimize", "flux_penalty", "_flux_penalty", "double", "0.35", "none", "", "FALSE", "", "", "", "Flux overage penalty", "Relative weight in the objective function given to flux intensity over the allowable limit"},
	{"optimize", "gs_refine_ratio", "_gs_refine_ratio", "double", "", "none", "", "FALSE", "", "", "", "Refinement relative bounding box", "The relative step size of the refined area during refinement simulations. More iterations will allow greater refinement"},
	{"optimize", "max_desc_iter", "_max_desc_iter", "int", "20", "none", "", "FALSE", "", "", "", "Max. no. continuous descent steps", "Maximum number of steps along the direction of steepest descent before recalculating the response surface"},
	{"optimize", "max_gs_iter", "_max_gs_iter", "int", "5", "none", "", "FALSE", "", "", "", "Max. refinement iterations", "Maximum number of golden section iterations to refine the position of a local minimum"},
	{"optimize", "max_iter", "_max_iter", "int", "10", "none", "", "FALSE", "", "", "", "Maximum total iteration loops", "Maximum number of times the optimization can iterate"},
	{"optimize", "max_step", "_max_step", "double", "0.02", "none", "", "FALSE", "", "", "", "Maximum relative step size", "Maximum total relative step size during optimization"},
	{"optimize", "power_penalty", "_power_penalty", "double", "0.5", "none", "", "FALSE", "", "", "", "Power shortage penalty", "Relative weight in the objective function given to power to the receiver below the required minimum"},
	{"parametric", "class_name", "_class_name", "string", "Parametric Simulation", "none", "", "FALSE", "", "", "", "Class name", "Class name"},
	{"parametric", "eff_file_name", "_eff_file_name", "string", "eff_array.dat", "", "", "FALSE", "", "", "", "Efficiency file name", "Name of the output file containing the efficiency matrix"},
	{"parametric", "flux_file_name", "_flux_file_name", "string", "fluxmap.csv", "", "", "FALSE", "", "", "", "Fluxmap file name", "Name of the output file containing the fluxmap data"},
	{"parametric", "fluxmap_format", "_fluxmap_format", "int", "0", "", "", "FALSE", "combo", "SAM format=0;12x10 array=1;Specified dimensions=2", "", "Fluxmap data dimensions", "Dimensions of the fluxmap data (rows,cols)"},
	{"parametric", "is_fluxmap_norm", "_is_fluxmap_norm", "bool", "TRUE", "", "", "FALSE", "checkbox", "", "", "Normalize flux data", "Flux data is reported as normalized"},
	{"parametric", "par_save_field_img", "_par_save_field_img", "bool", "FALSE", "none", "", "FALSE", "checkbox", "", "", "Save field efficiency image", "Save field efficiency image"},
	{"parametric", "par_save_flux_dat", "_par_save_flux_dat", "bool", "FALSE", "none", "", "FALSE", "checkbox", "", "", "Save receiver flux data", "Save receiver flux data"},
	{"parametric", "par_save_flux_img", "_par_save_flux_img", "bool", "FALSE", "none", "", "FALSE", "checkbox", "", "", "Save receiver flux image", "Save receiver flux image"},
	{"parametric", "par_save_helio", "_par_save_helio", "bool", "FALSE", "none", "", "FALSE", "checkbox", "", "", "Save heliostat performance data", "Save detailed heliostat performance data for each run"},
	{"parametric", "par_save_summary", "_par_save_summary", "bool", "FALSE", "none", "", "FALSE", "checkbox", "", "", "Save performance summary information", "Save detailed system performance data to a file for each run"},
	{"parametric", "sam_out_dir", "_sam_out_dir", "string", "", "", "", "FALSE", "", "", "", "Output directory", "Output directory"},
	{"parametric", "user_par_values", "_user_par_values", "string", "", "none", "", "FALSE", "", "", "", "User parametric values", "User parametric values"},
	{"plant", "class_name", "_class_name", "string", "Power Cycle and BOP", "none", "", "FALSE", "", "", "", "Class name", "Class name"},
	{"plant", "eta_cycle", "_eta_cycle", "double", "0.425", "none", "(0.,1]", "TRUE", "", "", "", "Rated cycle conversion efficiency", "Thermodynamic efficiency of the power cycle, including feedwater pumps and cooling equipment parasitics"},
	{"plant", "hours_tes", "_hours_tes", "double", "6", "hr", "[0.,100]", "TRUE", "", "", "", "Hours of full-load thermal storage", "Capacity of Hours of thermal storage operation at full cycle output"},
	{"plant", "par_factor", "_par_factor", "double", "0.87", "none", "(0.,1]", "TRUE", "", "", "", "Estimated gross to net conversion factor", "Estimated ratio of net power output to gross power output at design"},
	{"plant", "power_gross", "_power_gross", "double", "115", "MWe", "(0,9e9]", "FALSE", "", "", "", "Design turbine gross output", "Rated nameplate design gross turbine electric output, not accounting for parasitic losses"},
	{"plant", "power_net", "_power_net", "double", "100", "MWe", "(0,9e9]", "FALSE", "", "", "", "Estimated net output at design", "Estimated net electric power at design, accounting for all parasitic losses"},
	{"plant", "power_net_max", "_power_net_max", "double", "100", "MWe", "[0,9e9]", "FALSE", "", "", "", "Maximum net power for optimization", "Maximum net electric power rating considered for optimization - calculated from Layout page"},
	{"plant", "power_net_min", "_power_net_min", "double", "100", "MWe", "[0,9e9]", "FALSE", "", "", "", "Minimum net power for optimization", "Minimum net electric power rating considered for optimization - calculated from Layout page"},
	{"plant", "solar_mult", "_solar_mult", "double", "1.9", "none", "(0.,100]", "TRUE", "", "", "", "Solar multiple", "Ratio of thermal power output from the solar field to power cycle thermal input at design"},
	{"receiver", "absorber_area", "_absorber_area", "double", "0", "m2", "[-9e9,9e9]", "FALSE", "", "", "", "Receiver absorber area", "Effective area of the receiver absorber panels"},
	{"receiver", "absorptance", "_absorptance", "double", "0.94", "none", "(0.,1.]", "TRUE", "", "", "", "Receiver thermal absorptance", "Energy absorbed by the receiver surface before accounting for radiation/convection losses"},
	{"receiver", "accept_ang_type", "_accept_ang_type", "int", "0", "none", "", "TRUE", "combo", "Rectangular=0;Elliptical=1", "", "Receiver acceptance angles shape", "Receiver angular acceptance window defines angles about the aperture normal, can be rectangular or elliptical shape"},
	{"receiver", "accept_ang_x", "_accept_ang_x", "double", "180", "deg", "[0,180]", "TRUE", "", "", "", "Receiver horizontal acceptance angle", "Acceptance angle of the receiver in the horizontal direction (in aperture coordinates)"},
	{"receiver", "accept_ang_y", "_accept_ang_y", "double", "180", "deg", "[0,180]", "TRUE", "", "", "", "Receiver vertical acceptance angle", "Acceptance angle of the receiver in the vertical direction (in aperture coordinates)"},
	{"receiver", "aperture_type", "_aperture_type", "int", "0", "", "", "TRUE", "combo", "Rectangular=0;Elliptical=1", "", "Aperture geometry shape", "The shape of the receiver aperture"},
	{"receiver", "aspect_opt_max", "_aspect_opt_max", "double", "2", "m", "[0.,1000.]", "FALSE", "", "", "X", "Maximum receiver aspect ratio", "Maximum receiver aspect ratio during optimization"},
	{"receiver", "aspect_opt_min", "_aspect_opt_min", "double", "0.5", "m", "[0.,1000.]", "FALSE", "", "", "X", "Minimum receiver aspect ratio", "Minimum receiver aspect ratio during optimization"},
	{"receiver", "class_name", "_class_name", "string", "Receiver", "none", "", "FALSE", "", "", "", "Class name", "Class name"},
	{"receiver", "height_opt_max", "_height_opt_max", "double", "30", "m", "[0.,1000.]", "FALSE", "", "", "X", "Maximum receiver height", "Maximum receiver height during optimization"},
	{"receiver", "height_opt_min", "_height_opt_min", "double", "5", "m", "[0.,1000.]", "FALSE", "", "", "X", "Minimum receiver height", "Minimum receiver height during optimization"},
	{"receiver", "id", "_id", "int", "-1", "", "[-1,9e99]", "FALSE", "", "", "", "Template ID", "Template ID"},
	{"receiver", "is_aspect_opt", "_is_aspect_opt", "bool", "TRUE", "", "", "FALSE", "checkbox", "", "", "Optimize receiver aspect ratio", "Optimize receiver aspect ratio (height / width)"},
	{"receiver", "is_aspect_restrict", "_is_aspect_restrict", "bool", "FALSE", "", "", "FALSE", "checkbox", "", "X", "Restrict aspect ratio range", "Restrict aspect ratio range (height / width)"},
	{"receiver", "is_enabled", "_is_enabled", "bool", "TRUE", "", "", "FALSE", "", "", "", "Is template enabled?", "Is template enabled?"},
	{"receiver", "is_height_opt", "_is_height_opt", "bool", "TRUE", "", "", "FALSE", "checkbox", "", "", "Optimize receiver height", "Optimize receiver height"},
	{"receiver", "is_height_restrict", "_is_height_restrict", "bool", "FALSE", "", "", "FALSE", "checkbox", "", "X", "Restrict receiver height range", "Restrict receiver height range"},
	{"receiver", "is_open_geom", "_is_open_geom", "bool", "FALSE", "", "", "FALSE", "checkbox", "", "X", "Limit receiver panel span angle", "If true, the receiver is represented by an arc rather than a closed circle/polygon"},
	{"receiver", "is_polygon", "_is_polygon", "bool", "FALSE", "", "", "TRUE", "checkbox", "", "X", "Represent receiver as polygon", "Receiver geometry is represented as discrete polygon of N panels rather than continuous arc"},
	{"receiver", "n_panels", "_n_panels", "int", "12", "none", "[3,30]", "TRUE", "", "", "X", "Number of receiver panels", "Number of receiver panels (polygon facets) for a polygonal receiver geometry"},
	{"receiver", "optical_height", "_opt_height", "double", "180", "m", "(0.,1000.]", "FALSE", "", "", "", "Receiver optical height", "Calculated height of the centerline of the receiver above the plane of the heliostats"},
	{"receiver", "panel_rotation", "_panel_rotation", "double", "0", "deg", "[-180.,180.]", "TRUE", "", "", "X", "Receiver panel azimuthal orientation", "Azimuth angle between the normal vector to the primary 'north' panel and North"},
	{"receiver", "peak_flux", "_peak_flux", "double", "800", "kW/m2", "(0.,9e9]", "TRUE", "", "", "", "Allowable peak flux", "Maximum allowable flux intensity on any portion of the receiver surface"},
	{"receiver", "piping_loss", "_piping_loss", "double", "0", "MW", "", "FALSE", "", "", "", "Receiver piping loss", "Thermal loss from non-absorber receiver piping"},
	{"receiver", "piping_loss_coef", "_piping_loss_coef", "double", "10.2", "kW/m", "[0,9e9]", "TRUE", "", "", "", "Receiver piping loss coefficient", "Loss per meter of tower height"},
	{"receiver", "piping_loss_const", "_piping_loss_const", "double", "0", "kW", "[0,9e9]", "TRUE", "", "", "", "Receiver piping loss constant", "Constant thermal loss due to piping - doesn't scale with tower height"},
	{"receiver", "rec_aspect", "_rec_aspect", "double", "1.2", "none", "(0.,9e9]", "TRUE", "", "", "", "Receiver aspect ratio (H/W)", "Ratio of receiver height to width"},
	{"receiver", "rec_azimuth", "_rec_az", "double", "0", "deg", "[-180.,180]", "TRUE", "", "", "", "Receiver orientation azimuth", "Receiver azimuth orientation: 0 deg is north, positive clockwise"},
	{"receiver", "rec_cav_cdepth", "_rec_cav_cdepth", "double", "0", "m", "[-100.,100]", "TRUE", "", "", "", "Cavity curvature centroid offset", "Offset of centroid of cavity absorber surface from the aperture plane. (Positive->Increased depth)"},
	{"receiver", "rec_cav_rad", "_rec_cav_rad", "double", "7.75", "m", "(0.,100]", "TRUE", "", "", "", "Receiver cavity curvature radius", "Radius of the receiver cavity absorbing surface"},
	{"receiver", "rec_diameter", "_d", "double", "15.5", "m", "[0.,1000.]", "TRUE", "", "", "", "Receiver diameter", "Receiver diameter for cylindrical receivers"},
	{"receiver", "rec_elevation", "_rec_elevation", "double", "0", "deg", "[-90.,90.]", "TRUE", "", "", "", "Receiver orientation elevation", "Receiver elevation orientation: 0 deg to the horizon, negative rotating downward"},
	{"receiver", "rec_height", "_h", "double", "22", "m", "(0.,1000.]", "TRUE", "", "", "", "Receiver height", "Height of the absorbing component"},
	{"receiver", "rec_name", "_rec_name", "string", "Receiver 1", "", "", "FALSE", "", "", "", "Receiver template name", "Receiver template name"},
	{"receiver", "rec_offset_x", "_rec_offset_x", "double", "0", "m", "[-9e9,9e9]", "TRUE", "", "", "", "Receiver positioning offset - X axis", "Offset of receiver center in the East(+)/West(-) direction from the tower"},
	{"receiver", "rec_offset_y", "_rec_offset_y", "double", "0", "m", "[-9e9,9e9]", "TRUE", "", "", "", "Receiver positioning offset - Y axis", "Offset of receiver center in the North(+)/South(-) direction from the tower"},
	{"receiver", "rec_offset_z", "_rec_offset_z", "double", "0", "m", "[-9e9,9e9]", "TRUE", "", "", "", "Receiver positioning offset - Z axis", "Offset of the receiver center in the vertical direction, positive upwards"},
	{"receiver", "rec_type", "_rec_type", "int", "0", "none", "[0,5]", "FALSE", "combo", "External cylindrical=0;Flat plate=2", "", "Receiver type", "Receiver geometrical configuration"},
	{"receiver", "rec_width", "_w", "double", "15.5", "m", "[0.,1000.]", "TRUE", "", "", "", "Receiver width", "Receiver width for cavity or flat receivers"},
	{"receiver", "span_max", "_span_max", "double", "180", "deg", "[-180.,180.]", "TRUE", "", "", "X", "Max. receiver panel span angle", "Maximum (CW) bound of the arc defining the receiver surface"},
	{"receiver", "span_min", "_span_min", "double", "-180", "deg", "[-180.,180.]", "TRUE", "", "", "X", "Min. receiver panel span angle", "Minimum (CCW) bound of the arc defining the receiver surface"},
	{"receiver", "therm_loss", "_therm_loss", "double", "0", "MW", "", "FALSE", "", "", "", "Design-point thermal loss", "Receiver thermal loss at design"},
	{"receiver", "therm_loss_base", "_therm_loss_base", "double", "30", "kW/m2", "[0,9e9]", "TRUE", "", "", "", "Design point receiver thermal loss", "Thermal loss from the receiver at design-point conditions"},
	{"receiver", "therm_loss_load", "_therm_loss_load", "matrix_t<double>", "1,0,0,0", "none", "", "FALSE", "", "", "", "Load-based thermal loss adjustment", "Temperature-dependant thermal loss"},
	{"receiver", "therm_loss_wind", "_therm_loss_wind", "matrix_t<double>", "1,0,0,0", "none", "", "FALSE", "", "", "", "Wind-based thermal loss adjustment", "Wind speed-dependant thermal loss"},
	{"solarfield", "accept_max", "_accept_max", "double", "180", "deg", "[-180.,180.]", "TRUE", "", "", "", "Maximum solar field extent angle", "Upper bound of the angular range containing the heliostat field"},
	{"solarfield", "accept_min", "_accept_min", "double", "-180", "deg", "[-180.,180.]", "TRUE", "", "", "", "Minimum solar field extent angle", "Lower bound of the angular range containing the heliostat field"},
	{"solarfield", "az_spacing", "_az_spacing", "double", "2", "none", "[1.,1000.]", "TRUE", "", "", "", "Azimuthal spacing factor", "Azimuthal spacing factor for the first row of heliostats after a reset. Heliostats separated by heliostat width times this factor."},
	{"solarfield", "class_name", "_class_name", "string", "Solar Field", "none", "", "FALSE", "", "", "", "Class name", "Class name"},
	{"solarfield", "des_sim_detail", "_des_sim_detail", "int", "5", "none", "[0,4]", "TRUE", "combo", "Subset of days/hours=2;Single simulation point=1;Do not filter heliostats=0;Annual simulation=3;Limited annual simulation=4;Representative profiles=5;Efficiency map + annual=6", "", "Optimization simulations", "Simulation detail for placing heliostats (see definitions in options spreadsheet)"},
	{"solarfield", "des_sim_ndays", "_des_sim_ndays", "int", "4", "none", "(1,365]", "TRUE", "", "", "", "Number of days to simulate", "For limited annual simulation, the number of evenly spaced days to simulate"},
	{"solarfield", "des_sim_nhours", "_des_sim_nhours", "int", "2", "none", "[1,5]", "TRUE", "", "", "", "Simulation hour frequency", "Simulation will run with the specified hourly frequency (1=every hour, 2=every other hour...)"},
	{"solarfield", "dni_des", "_dni_des", "double", "950", "W/m2", "(0.,1300.]", "TRUE", "", "", "", "Design-point DNI value", "DNI value at which the design-point receiver thermal power is achieved"},
	{"solarfield", "hsort_method", "_hsort_method", "int", "7", "none", "", "TRUE", "combo", "Power to receiver=0;Total efficiency=1;Cosine efficiency=2;Attenuation efficiency=3;Intercept efficiency=4;Blocking efficiency=5;Shadowing efficiency=6;TOU-weighted power=7", "", "Heliostat selection criteria", "Select the criteria by which heliostats will be included in the solar field layout."},
	{"solarfield", "is_opt_zoning", "_is_opt_zoning", "bool", "TRUE", "none", "", "FALSE", "checkbox", "", "", "Enable optical layout zone method", "Enables grouping of heliostats into zones for intercept factor calculation during layout only"},
	{"solarfield", "is_power_opt", "_is_power_opt", "bool", "FALSE", "none", "", "FALSE", "checkbox", "", "X", "Optimize power output", "Vary the power output during optimization to identify optimal level?"},
	{"solarfield", "is_power_restrict", "_is_power_restrict", "bool", "FALSE", "none", "", "FALSE", "checkbox", "", "X", "Restrict power output search", "Restrict the search range for power output to the indicated limits"},
	{"solarfield", "is_prox_filter", "_is_prox_filter", "bool", "FALSE", "none", "", "TRUE", "checkbox", "", "", "Apply proximity filter", "Post-process the layout to select heliostats that are closer to the tower."},
	{"solarfield", "is_tht_opt", "_is_tht_opt", "bool", "TRUE", "none", "", "FALSE", "checkbox", "", "", "Optimize tower height", "Vary the tower height during optimization to identify optimal level?"},
	{"solarfield", "is_tht_restrict", "_is_tht_restrict", "bool", "FALSE", "none", "", "FALSE", "checkbox", "", "X", "Restrict tower height search", "Restrict the search range for tower height to the indicated limits"},
	{"solarfield", "layout_data", "_layout_data", "string", "", "", "", "FALSE", "", "", "", "Layout data in string form", "Layout data in string form"},
	{"solarfield", "layout_method", "_layout_method", "int", "1", "none", "[0,99]", "FALSE", "combo", "Radial Stagger=1;Cornfield=2;User-defined=3", "", "Layout method", "Field layout method"},
	{"solarfield", "max_zone_size_az", "_max_zone_size_az", "double", "1", "tower-ht", "(0,100]", "TRUE", "", "", "", "Max. optical layout zone size - azimuthal", "Maximum zone size (azimuthal direction) for grouping optical intercept factor calculations"},
	{"solarfield", "max_zone_size_rad", "_max_zone_size_rad", "double", "1", "tower-ht", "(0,100]", "TRUE", "", "", "", "Max. optical layout zone size - radial", "Maximum zone size (radial direction) for grouping optical intercept factor calculations"},
	{"solarfield", "min_zone_size_az", "_min_zone_size_az", "double", "0.1", "tower-ht", "(0,100]", "TRUE", "", "", "", "Min. optical layout zone size - azimuthal", "Minimum zone size (azimuthal direction) for grouping optical intercept factor calculations"},
	{"solarfield", "min_zone_size_rad", "_min_zone_size_rad", "double", "0.1", "tower-ht", "(0,100]", "TRUE", "", "", "", "Min. optical layout zone size - radial", "Minimum zone size (radial direction) for grouping optical intercept factor calculations"},
	{"solarfield", "prox_filter_frac", "_prox_filter_frac", "double", "0.03", "none", "[0.,1)", "TRUE", "", "", "", "Proximity filter fraction", "Fraction of heliostats to subject to proximity filter."},
	{"solarfield", "q_des", "_q_des", "double", "500", "MWt", "(0.,99999.]", "TRUE", "", "", "", "Solar field design power", "Design thermal power delivered from the solar field"},
	{"solarfield", "q_des_opt_max", "_q_des_opt_max", "double", "1000", "MWt", "(0.,99999.]", "FALSE", "", "", "X", "Maximum solar field design power", "Maximum possible solar field design power during optimzation"},
	{"solarfield", "q_des_opt_min", "_q_des_opt_min", "double", "100", "MWt", "(0.,99999.]", "FALSE", "", "", "X", "Minimum solar field design power", "Minimum possible solar field design power during optimzation"},
	{"solarfield", "rad_spacing_method", "_rad_spacing_method", "int", "2", "none", "[1,3]", "TRUE", "combo", "Eliminate blocking=2;DELSOL Empirical Fit=1;DELSOL Revised Fit=4", "", "Radial spacing method", "Method for determining radial spacing during field layout for radial-stagger"},
	{"solarfield", "row_spacing_x", "_row_spacing_x", "double", "1.1", "none", "(1,1000.]", "TRUE", "", "", "", "Heliostat spacing factor - X direction", "Separation between adjacent heliostats in the X-direction, multiplies heliostat radius"},
	{"solarfield", "row_spacing_y", "_row_spacing_y", "double", "1.1", "none", "(1,1000.]", "TRUE", "", "", "", "Heliostat spacing factor - Y direction", "Separation between adjacent heliostats in the Y-direction, multiplies heliostat radius"},
	{"solarfield", "shadow_height", "_towL", "double", "_tht", "m", "(0.,1000.]", "FALSE", "", "", "", "Tower shadow height", "Effective tower height for shadowing calculations"},
	{"solarfield", "shadow_width", "_towD", "double", "16", "m", "(0.,1000.]", "FALSE", "", "", "", "Tower shadow width", "Effective tower diameter for shadowing calculations"},
	{"solarfield", "sim_step_data", "_sim_step_data", "WeatherData", "", "none", "", "FALSE", "", "", "", "Data used for design simulations", "Data used for design simulations"},
	{"solarfield", "sim_time_step", "_sim_time_step", "double", "0", "sec", "", "FALSE", "", "", "", "Simulation weather data time step", "Simulation weather data time step"},
	{"solarfield", "spacing_reset", "_spacing_reset", "double", "1.33", "none", "(1.,1000.]", "TRUE", "", "", "", "Azimuthal spacing reset limit", "For heliostat layout - ratio of maximum to initial azimuthal spacing before starting new compressed row"},
	{"solarfield", "sun_loc_des", "_sun_loc_des", "int", "0", "none", "", "TRUE", "combo", "Summer solstice=0;Equinox=1;Winter solstice=2;Zenith=3;Other..=4", "", "Sun location at design point", "Sun location when thermal power rating is achieved"},
	{"solarfield", "sun_loc_des_az", "_sun_loc_des_az", "double", "180", "deg", "[-180.,180.]", "TRUE", "", "", "", "Design-point solar azimuth", "Solar azimuth angle at the design point"},
	{"solarfield", "sun_loc_des_el", "_sun_loc_des_el", "double", "85", "deg", "[0.,90]", "TRUE", "", "", "", "Design-point solar elevation", "Solar elevation angle at the design point"},
	{"solarfield", "template_rule", "_template_rule", "int", "0", "", "", "TRUE", "combo", "Use single template=0;Specified range=1;Even radial distribution=2", "", "Heliostat geometry distribution", "Method for distributing heliostat geometry templates in the field"},
	{"solarfield", "tht", "_tht", "double", "180", "m", "(0.,1000.]", "TRUE", "", "", "", "Tower optical height", "Average height of the tower receiver centerline above the base heliostat pivot point elevation"},
	{"solarfield", "tht_opt_max", "_tht_opt_max", "double", "225", "m", "(0.,1000.]", "TRUE", "", "", "X", "Maximum tower height", "Maximum allowable tower height during optimization"},
	{"solarfield", "tht_opt_min", "_tht_opt_min", "double", "125", "m", "(0.,1000.]", "TRUE", "", "", "X", "Minimum tower height", "Minimum allowable tower height during optimization"},
	{"solarfield", "xy_field_shape", "_xy_field_shape", "int", "0", "", "[0,2]", "TRUE", "combo", "Hexagon=0;Rectangle=1;Undefined=2", "", "Heliostat field layout shape", "Enforced shape of the heliostat field"},
	{"solarfield", "xy_rect_aspect", "_xy_rect_aspect", "double", "1", "none", "(0.,1000.]", "TRUE", "", "", "", "Layout aspect ratio (Y/X)", "Aspect ratio of the rectangular field layout (height in Y / width in X)"},
	{"solarfield", "zone_div_tol", "_zone_div_tol", "double", "0.001", "none", "[0.001,1]", "TRUE", "", "", "", "Optical layout zone mesh tolerance", "Allowable variation in optical intercept factor within a layout zone"},
#if _CUSTOM_REC == 1
	{"custom_rec", "A_proj", "_A_proj", "double", "0", "m2", "", "FALSE", "", "", "", "Projected absorber area", "Projected absorber area"},
	{"custom_rec", "A_tot", "_A_tot", "double", "0", "m2", "", "FALSE", "", "", "", "Total absorber surface area", "Total absorber surface area"},
	{"custom_rec", "base_name", "_base_name", "string", "nbb_co2", "none", "", "TRUE", "", "", "", "Output data directory base", "Base name for output data. Directory will be appended with simulation number for multiple sims."},
	{"custom_rec", "basis_method", "_basis_method", "int", "0", "none", "", "TRUE", "combo", "Average=0;Median=1;Peak=2;Tube design point=3;Specified=4", "", "Flux absorption basis value", "Metric to use as base flux value in determining profile quality"},
	{"custom_rec", "basis_specified", "_basis_specified", "double", "0", "kW", "", "TRUE", "", "", "", "Specified flux absorption basis", "Metric to use as base flux value in determining profile quality"},
	{"custom_rec", "cav_depth", "_cav_depth", "double", "3", "m", "", "TRUE", "", "", "", "Cavity depth", "Length between aperture and back wall"},
	{"custom_rec", "circ_min", "_circ_min", "double", "0", "none", "[0.,1.]", "TRUE", "", "", "", "Normalized profile minimum", "Minimum flux value (multiplied by max. value) in the circumferential profile."},
	{"custom_rec", "circ_profile", "_circ_profile", "int", "0", "none", "", "TRUE", "combo", "Sinusoidal=0;Square=1", "", "Circumferential flux profile", "Method for generating circumferential flux profile based on available data points"},
	{"custom_rec", "circ_res", "_circ_res", "int", "20", "none", "[2,9999]", "TRUE", "", "", "", "Circumferential simulation points", "Number of points in the circumferential flux profile"},
	{"custom_rec", "class_name", "_class_name", "string", "NBB s-CO2 Receiver", "none", "", "FALSE", "", "", "", "Class name", "Class name"},
	{"custom_rec", "D_header", "_D_header", "double", "0.1", "m", "", "TRUE", "", "", "", "Header diameter", "Header diameter"},
	{"custom_rec", "d_tube", "_d_tube", "double", "0.02", "m", "", "TRUE", "", "", "", "Individual tube outer diameter", "Individual tube outer diameter"},
	{"custom_rec", "design_location", "_design_location", "int", "0", "none", "", "TRUE", "combo", "Peak flux=0;Circumferential delta=1", "", "Flux criteria for design point", "Flux criteria to determine the tube design point location"},
	{"custom_rec", "ees_path", "_ees_path", "string", "C:\\EES32\\ees.exe", "none", "", "FALSE", "path", "", "", "EES executable location", "EES executable location"},
	{"custom_rec", "enable_custom", "_enable_custom", "bool", "FALSE", "none", "", "FALSE", "checkbox", "", "", "Enable custom receiver geometry", "Use the custom receiver geometry functionality"},
	{"custom_rec", "enable_ees", "_enable_ees", "bool", "FALSE", "none", "", "TRUE", "checkbox", "", "", "Enable tube strain simulations", "Run the tube strain model according to the specified settings"},
	{"custom_rec", "est_flux", "_est_flux", "double", "0", "kW/m2", "", "FALSE", "", "", "", "Estimated average flux", "Average flux on absorber panels at design"},
	{"custom_rec", "export_quality", "_export_quality", "bool", "TRUE", "none", "", "TRUE", "checkbox", "", "", "Export flux profile quality results", "Save tabulated flux quality results to the output directory"},
	{"custom_rec", "f_h_bend", "_f_h_bend", "double", "0.9", "none", "", "TRUE", "", "", "", "Bend vertical fill", "Bend vertical fill"},
	{"custom_rec", "f_offset_zm", "_f_offset_zm", "double", "0", "none", "", "TRUE", "", "", "", "Absorber back wall offset factor", "Fraction of the total cavity depth by which the absorber is displaced from the back wall"},
	{"custom_rec", "f_offset_zp", "_f_offset_zp", "double", "0", "none", "", "TRUE", "", "", "", "Absorber aperture offset factor", "Fraction of the total cavity depth by which the absorber is displaced from the aperture"},
	{"custom_rec", "f_shield", "_f_shield", "double", "0", "none", "", "FALSE", "", "", "", "Shield aperture occupancy fraction", "Shield aperture occupancy fraction"},
	{"custom_rec", "f_x_abs", "_f_x_abs", "double", "1", "none", "", "TRUE", "", "", "", "Absorber horizontal occupancy factor", "Absorber horizontal occupancy factor"},
	{"custom_rec", "f_x_sep", "_f_x_sep", "double", "1", "none", "", "TRUE", "", "", "", "Vert. Panel internal spacing factor", "Factor multiplying spacing length between vertical panels. Max should be (n-1)/(n-3) for n>3"},
	{"custom_rec", "f_y_abs", "_f_y_abs", "double", "1", "none", "", "TRUE", "", "", "", "Horiz. Panel internal spacing factor", "Factor multiplying spacing length between horizontal panels. Max should be (n-1)/(n-3) for n>3"},
	{"custom_rec", "flux_adjust", "_flux_adjust", "double", "0", "none", "", "FALSE", "", "", "", "Flux magnitude multiplier", "Flux magnitude multiplier"},
	{"custom_rec", "generate_plots", "_generate_plots", "bool", "TRUE", "none", "", "FALSE", "checkbox", "", "", "Generate surface flux plots", "Generate surface flux plots"},
	{"custom_rec", "generate_profiles", "_generate_profiles", "bool", "FALSE", "none", "", "FALSE", "checkbox", "", "", "Generate surface flux data files", "Generate surface flux data files"},
	{"custom_rec", "h_rec", "_h_rec", "double", "8", "m", "", "FALSE", "", "", "", "Receiver total height", "Receiver total height"},
	{"custom_rec", "header_domain", "_header_domain", "int", "0", "none", "", "TRUE", "combo", "Adjacent half panels=0;Adjacent full panels=1;Single unit surface=2", "", "Header supply domain", "Method for dividing a flux panel into header sections"},
	{"custom_rec", "inlet_temp", "_inlet_temp", "double", "470", "C", "", "TRUE", "", "", "", "Receiver inlet temperature", "Design-point receiver inlet temperature"},
	{"custom_rec", "is_results_window", "_is_results_window", "bool", "TRUE", "none", "", "FALSE", "checkbox", "", "", "Show results window", "Show results window"},
	{"custom_rec", "L_shield_ext", "_L_shield_ext", "double", "0.05", "m", "", "TRUE", "", "", "", "Shield additional coverage depth", "Shield additional coverage depth"},
	{"custom_rec", "link_opt_props", "_link_opt_props", "bool", "FALSE", "none", "", "TRUE", "checkbox", "", "", "Separators use absorber optics", "Overwrite the specified separator optical properties with absorber properties"},
	{"custom_rec", "n_abs", "_n_abs", "int", "8", "none", "[2,999]", "TRUE", "", "", "", "Number of absorber racks vertically", "Number of absorber racks vertically"},
	{"custom_rec", "n_sep", "_n_sep", "int", "2", "none", "[2,999]", "TRUE", "", "", "", "Number of optical separation panels", "Number of optical separation panels"},
	{"custom_rec", "N_tubes", "_N_tubes", "int", "0", "none", "", "FALSE", "", "", "", "Number of tubes in the receiver", "Number of tubes in the receiver"},
	{"custom_rec", "outlet_temp", "_outlet_temp", "double", "650", "C", "", "TRUE", "", "", "", "Receiver outlet temperature", "Design-point receiver outlet temperature"},
	{"custom_rec", "p_out", "p_out", "double", "0", "bar", "", "FALSE", "", "", "", "Tube outlet pressure", "Tube outlet pressure"},
	{"custom_rec", "profile_name", "profile_name", "string", "none", "none", "", "FALSE", "", "", "", "Flux profile location", "Flux profile location"},
	{"custom_rec", "q_ray", "_q_ray", "double", "100", "W", "", "FALSE", "", "", "", "Power per ray", "Power per ray"},
	{"custom_rec", "quality_method", "_quality_method", "int", "0", "none", "", "TRUE", "combo", "All panels together=0;Split by panel=1;Split by header=2", "", "Flux quality evaluation domain", "Method for calculating the quality of the flux profile"},
	{"custom_rec", "rec_mass_flow", "_rec_mass_flow", "double", "0", "kg/s", "", "FALSE", "", "", "", "Receiver mass flow rate", "Mass flow rate of the CO2 through the entire receiver"},
	{"custom_rec", "rec_pressure", "_rec_pressure", "double", "25", "MPa", "[7.5,40]", "TRUE", "", "", "", "Receiver operating pressure", "Turbine inlet pressure"},
	{"custom_rec", "rho_abs", "_rho_abs", "double", "0.5", "none", "", "TRUE", "", "", "", "Absorber reflectivity", "Absorber reflectivity"},
	{"custom_rec", "rho_cav", "_rho_cav", "double", "0.95", "none", "", "TRUE", "", "", "", "Cavity wall reflectivity", "Cavity wall reflectivity"},
	{"custom_rec", "rho_sep", "_rho_sep", "double", "0.95", "none", "", "TRUE", "", "", "", "Separator reflectivity", "Separator reflectivity"},
	{"custom_rec", "rho_shield", "_rho_shield", "double", "0.9", "none", "", "TRUE", "", "", "", "Shield reflectivity", "Shield reflectivity"},
	{"custom_rec", "sep_are_abs", "_sep_are_abs", "bool", "FALSE", "none", "", "TRUE", "checkbox", "", "", "Treat separators as absorbers", "Treat separators as absorbers"},
	{"custom_rec", "sigma_s_abs", "_sigma_s_abs", "double", "5", "mrad", "", "TRUE", "", "", "", "Absorber specularity", "Absorber specularity"},
	{"custom_rec", "sigma_s_cav", "_sigma_s_cav", "double", "0.75", "mrad", "", "TRUE", "", "", "", "Cavity wall specularity", "Cavity wall specularity"},
	{"custom_rec", "sigma_s_sep", "_sigma_s_sep", "double", "0.75", "mrad", "", "TRUE", "", "", "", "Separator specularity", "Separator specularity"},
	{"custom_rec", "sigma_s_shield", "_sigma_s_shield", "double", "0.75", "mrad", "", "TRUE", "", "", "", "Shield specularity", "Shield specularity"},
	{"custom_rec", "sim_res", "_sim_res", "int", "20", "none", "[1,9999]", "TRUE", "", "", "", "Axial simulation points", "Simulation discretization along each flow path"},
	{"custom_rec", "T_eval_max", "T_eval_max", "double", "0", "C", "", "FALSE", "", "", "", "Maximum material temperature", "Maximum material temperature"},
	{"custom_rec", "T_surf_max", "T_surf_max", "double", "0", "C", "", "FALSE", "", "", "", "Maximum surface temperature", "Maximum surface temperature"},
	{"custom_rec", "tau_abs", "_tau_abs", "double", "0", "none", "", "TRUE", "", "", "", "Absorber transmissivity", "Absorber transmissivity"},
	{"custom_rec", "tau_cav", "_tau_cav", "double", "0", "none", "", "TRUE", "", "", "", "Cavity wall transmissivity", "Cavity wall transmissivity"},
	{"custom_rec", "tau_sep", "_tau_sep", "double", "0", "none", "", "TRUE", "", "", "", "Separator transmissivity", "Separator transmissivity"},
	{"custom_rec", "tau_shield", "_tau_shield", "double", "0", "none", "", "TRUE", "", "", "", "Shield transmissivity", "Shield transmissivity"},
	{"custom_rec", "theta_bend", "_theta_bend", "double", "120", "deg", "", "TRUE", "", "", "", "Absorber bend angle ", "Absorber bend angle "},
	{"custom_rec", "theta_shield", "_theta_shield", "double", "35", "deg", "", "TRUE", "", "", "", "Angle between shield surfaces", "Angle between shield surfaces"},
	{"custom_rec", "tube_length_abs", "_tube_length_abs", "double", "3", "m", "", "FALSE", "", "", "", "Absorber tube path length", "Total tubing length for a tube in the absorber panel"},
	{"custom_rec", "tube_length_sep", "_tube_length_sep", "double", "3", "m", "", "FALSE", "", "", "", "Separator tube path length", "Total tubing length for a tube in the separator panel"},
	{"custom_rec", "tube_material", "_tube_material", "int", "0", "", "", "TRUE", "combo", "Haynes 230=0;Stainless Steel 316=1", "", "Tube material", "Tube material"},
	{"custom_rec", "tube_mdot", "tube_mdot", "double", "0", "kg/s", "", "FALSE", "", "", "", "Tube mass flow rate at design", "Tube mass flow rate at design"},
	{"custom_rec", "tube_qdot", "tube_qdot", "double", "0", "W", "", "FALSE", "", "", "", "Energy absorbed in design tube", "Energy absorbed in design tube"},
	{"custom_rec", "tube_rough", "_tube_rough", "double", "3.00E-06", "m", "", "TRUE", "", "", "", "Tube internal roughness", "Tube internal roughness"},
	{"custom_rec", "tube_thickness", "tube_thickness", "double", "0", "m", "", "FALSE", "", "", "", "Calculated tube thickness", "Calculated tube thickness"},
	{"custom_rec", "w_rec", "_w_rec", "double", "8", "m", "", "FALSE", "", "", "", "Receiver total width", "Receiver total width"},
	{"custom_rec", "x_bins", "_x_bins", "int", "15", "none", "", "FALSE", "", "", "", "Number of surface bins (X)", "Number of surface bins (X)"},
	{"custom_rec", "y_bins", "_y_bins", "int", "15", "none", "", "FALSE", "", "", "", "Number of surface bins (Y)", "Number of surface bins (Y)"},
#endif
	{"--end--", "", "", "", "", "", "", "", "", "", "", "", ""}
};
