#include "core.h"

var_info vtab_standard_financial[] = {

/*   VARTYPE           DATATYPE         NAME                            LABEL                              UNITS     META                      GROUP          REQUIRED_IF                 CONSTRAINTS                      UI_HINTS*/
	{ SSC_INPUT,        SSC_NUMBER,      "analysis_years",              "Analyis period",                 "years",  "",                      "Financials",      "?=30",                   "INTEGER,MIN=0,MAX=50",          "" },
	{ SSC_INPUT,        SSC_NUMBER,      "fed_tax_rate",                "Federal tax rate",               "%",      "",                      "Financials",      "*",                      "MIN=0,MAX=100",                 "" },
	{ SSC_INPUT,        SSC_NUMBER,      "state_tax_rate",              "State tax rate",                 "%",      "",                      "Financials",      "*",                      "MIN=0,MAX=100",                 "" },
	{ SSC_INPUT,        SSC_NUMBER,      "property_tax_rate",           "Property tax rate",              "%",      "",                      "Financials",      "?=0.0",                  "MIN=0,MAX=100",                 "" },
	{ SSC_INPUT,        SSC_NUMBER,      "real_discount_rate",          "Real discount rate",             "%",      "",                      "Financials",      "*",                      "MIN=0,MAX=100",                 "" },
	{ SSC_INPUT,        SSC_NUMBER,      "inflation_rate",              "Inflation rate",                 "%",      "",                      "Financials",      "*",                      "MIN=0,MAX=100",                 "" },
	{ SSC_INPUT,        SSC_NUMBER,      "sales_tax_rate",              "Sales tax rate",                 "%",      "",                      "Financials",      "?=0.0",                  "MIN=0,MAX=100",                 "" },
	{ SSC_INPUT,        SSC_NUMBER,      "insurance_rate",              "Insurance rate",                 "%",      "",                      "Financials",      "?=0.0",                  "MIN=0,MAX=100",                 "" },
	{ SSC_INPUT,        SSC_NUMBER,      "salvage_percentage",          "Salvage value percentage",       "%",      "",                      "Financials",      "?=0.0",                  "MIN=0,MAX=100",                 "" },

	{ SSC_INPUT,        SSC_NUMBER,      "system_capacity",             "System nameplate capacity",      "kW",     "",                      "System",          "*",                      "POSITIVE",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "system_heat_rate",            "System heat rate",               "MMBTus/MWh", "",                  "System",          "?=0.0",                  "MIN=0",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "total_direct_cost",           "Total direct cost",              "$",      "",                      "Cost",            "*",                      "MIN=0",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "total_indirect_cost",         "Total indirect cost",            "$",      "",                      "Cost",            "*",                      "MIN=0",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "total_construction_interest", "Total construction interest",    "$",      "",                      "Cost",            "*",                      "MIN=0",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "total_direct_sales_tax",      "Total direct sales tax",         "$",      "",                      "Cost",            "*",                      "MIN=0",                                         "" },

var_info_invalid };

var_info vtab_oandm[] = {
/*   VARTYPE           DATATYPE         NAME                             LABEL                                UNITS      META                 GROUP          REQUIRED_IF                 CONSTRAINTS                      UI_HINTS*/
	
	{ SSC_INPUT,        SSC_ARRAY,       "om_fixed",                     "Fixed O&M Annual Amount",           "$/year",  "",                  "O&M",            "?=0.0",                 "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "om_fixed_escal",               "Fixed O&M Escalation",              "%/year",  "",                  "O&M",            "?=0.0",                 "",                                         "" },
	{ SSC_INPUT,        SSC_ARRAY,       "om_production",                "Production-based O&M Amount",       "$/MWh",   "",                  "O&M",            "?=0.0",                 "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "om_production_escal",          "Production-based O&M Escalation",   "%/year",  "",                  "O&M",            "?=0.0",                 "",                                         "" },
	{ SSC_INPUT,        SSC_ARRAY,       "om_capacity",                  "Capacity-based O&M Amount",         "$/kWcap", "",                  "O&M",            "?=0.0",                 "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "om_capacity_escal",            "Capacity-based O&M Escalation",     "%/year",  "",                  "O&M",            "?=0.0",                 "",                                         "" },
	{ SSC_INPUT,        SSC_ARRAY,		 "om_fuel_cost",                 "Fuel Cost",                         "$/MMBtu", "",                  "O&M",            "?=0.0",                 "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "om_fuel_cost_escal",           "Fuel Cost Escalation",              "%/year",  "",                  "O&M",            "?=0.0",                 "",                                         "" },

var_info_invalid };

var_info vtab_depreciation[] = {
/*   VARTYPE           DATATYPE         NAME                              LABEL                                 UNITS     META                                      GROUP             REQUIRED_IF                 CONSTRAINTS                      UI_HINTS*/

	{ SSC_INPUT,        SSC_NUMBER,      "depr_fed_type",                "Federal Depreciation Type",           "",       "0=none,1=macrs_half_year,2=sl,3=custom",  "Depreciation",      "?=0",                     "INTEGER,MIN=0,MAX=3",        "" },
	{ SSC_INPUT,        SSC_NUMBER,      "depr_fed_sl_years",            "Federal Depreciation SL Years",       "years",  "",                                        "Depreciation",      "?=7",                     "INTEGER,POSITIVE",           "" },
	{ SSC_INPUT,        SSC_NUMBER,      "depr_fed_custom",              "Federal Custom Depreciation",         "%/year", "",                                        "Depreciation",      "depr_fed_type=3",         "",                           "" },
	{ SSC_INPUT,        SSC_NUMBER,      "depr_sta_type",                "State Depreciation Type",             "",       "0=none,1=macrs_half_year,2=sl,3=custom",  "Depreciation",      "?=0",                     "INTEGER,MIN=0,MAX=3",        "" },
	{ SSC_INPUT,        SSC_NUMBER,      "depr_sta_sl_years",            "State Depreciation SL Years",         "years",  "",                                        "Depreciation",      "?=7",                     "INTEGER,POSITIVE",           "" },
	{ SSC_INPUT,        SSC_NUMBER,      "depr_sta_custom",              "State Custom Depreciation",           "%/year", "",                                        "Depreciation",      "depr_sta_type=3",         "",                           "" },

var_info_invalid };


var_info vtab_utility_rate[] = {

/*   VARTYPE           DATATYPE         NAME                         LABEL                              UNITS     META                      GROUP          REQUIRED_IF                 CONSTRAINTS                      UI_HINTS*/
	{ SSC_INPUT,        SSC_NUMBER,     "ur_buy_eq_sell",           "Force sell rate equal to buy",    "0/1",    "Enforce net metering",  "",             "?=1",                       "BOOLEAN",                       "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_monthly_fixed_charge",  "Monthly fixed charge",            "$",      "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_flat_buy_rate",         "Flat rate (buy)",                 "$/kWh",  "",                      "",             "*",                         "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_flat_sell_rate",        "Flat rate (sell)",                "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },

	{ SSC_INPUT,        SSC_NUMBER,     "ur_tou_enable",            "Enable time-of-use rates",        "0/1",    "",                      "",             "?=0",                       "BOOLEAN",                       "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tou_p1_buy_rate",       "TOU Period 1 Rate (buy)",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tou_p1_sell_rate",      "TOU Period 1 Rate (sell)",        "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tou_p2_buy_rate",       "TOU Period 2 Rate (buy)",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tou_p2_sell_rate",      "TOU Period 2 Rate (sell)",        "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tou_p3_buy_rate",       "TOU Period 3 Rate (buy)",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tou_p3_sell_rate",      "TOU Period 3 Rate (sell)",        "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tou_p4_buy_rate",       "TOU Period 4 Rate (buy)",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tou_p4_sell_rate",      "TOU Period 4 Rate (sell)",        "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tou_p5_buy_rate",       "TOU Period 5 Rate (buy)",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tou_p5_sell_rate",      "TOU Period 5 Rate (sell)",        "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tou_p6_buy_rate",       "TOU Period 6 Rate (buy)",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tou_p6_sell_rate",      "TOU Period 6 Rate (sell)",        "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tou_p7_buy_rate",       "TOU Period 7 Rate (buy)",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tou_p7_sell_rate",      "TOU Period 7 Rate (sell)",        "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tou_p8_buy_rate",       "TOU Period 8 Rate (buy)",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tou_p8_sell_rate",      "TOU Period 8 Rate (sell)",        "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tou_p9_buy_rate",       "TOU Period 9 Rate (buy)",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tou_p9_sell_rate",      "TOU Period 9 Rate (sell)",        "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_STRING,     "ur_tou_sched_weekday",     "TOU Weekday Schedule",            "",       "288 digits 0-9, 24x12", "",             "ur_tou_enable=1",           "TOUSCHED",                      "" },
	{ SSC_INPUT,        SSC_STRING,     "ur_tou_sched_weekend",     "TOU Weekend Schedule",            "",       "288 digits 0-9, 24x12", "",             "ur_tou_enable=1",           "TOUSCHED",                      "" },

	{ SSC_INPUT,        SSC_NUMBER,     "ur_dc_enable",             "Enable demand charges",           "0/1",    "",                      "",             "?=0",                       "BOOLEAN",                       "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_dc_fixed1",             "DC Fixed Rate January",           "$/kW,pk","",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_dc_fixed2",             "DC Fixed Rate February",          "$/kW,pk","",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_dc_fixed3",             "DC Fixed Rate March",             "$/kW,pk","",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_dc_fixed4",             "DC Fixed Rate April",             "$/kW,pk","",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_dc_fixed5",             "DC Fixed Rate May",               "$/kW,pk","",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_dc_fixed6",             "DC Fixed Rate June",              "$/kW,pk","",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_dc_fixed7",             "DC Fixed Rate July",              "$/kW,pk","",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_dc_fixed8",             "DC Fixed Rate August",            "$/kW,pk","",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_dc_fixed9",             "DC Fixed Rate September",         "$/kW,pk","",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_dc_fixed10",            "DC Fixed Rate October",           "$/kW,pk","",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_dc_fixed11",            "DC Fixed Rate November",          "$/kW,pk","",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_dc_fixed12",            "DC Fixed Rate December",          "$/kW,pk","",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_dc_p1",                 "DC TOU Rate Period 1",            "$/kW,pk","",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_dc_p2",                 "DC TOU Rate Period 2",            "$/kW,pk","",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_dc_p3",                 "DC TOU Rate Period 3",            "$/kW,pk","",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_dc_p4",                 "DC TOU Rate Period 4",            "$/kW,pk","",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_dc_p5",                 "DC TOU Rate Period 5",            "$/kW,pk","",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_dc_p6",                 "DC TOU Rate Period 6",            "$/kW,pk","",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_dc_p7",                 "DC TOU Rate Period 7",            "$/kW,pk","",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_dc_p8",                 "DC TOU Rate Period 8",            "$/kW,pk","",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_dc_p9",                 "DC TOU Rate Period 9",            "$/kW,pk","",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_STRING,     "ur_dc_sched_weekday",      "DC TOU Weekday Schedule",         "",       "288 digits 0-9, 24x12", "",             "ur_dc_enable=1",            "TOUSCHED",                      "" },
	{ SSC_INPUT,        SSC_STRING,     "ur_dc_sched_weekend",      "DC TOU Weekend Schedule",         "",       "288 digits 0-9, 24x12", "",             "ur_dc_enable=1",            "TOUSCHED",                      "" },

	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_enable",             "Enable tiered rates",             "0/1",    "",                      "",             "?=0",                       "BOOLEAN",                       "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_sell_type",          "Tiered rate sell mode",           "0,1,2",  "0=specified,1=tier1,2=lowest", "",      "?=0",                       "INTEGER,MIN=0,MAX=2",           "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_sell_rate",          "Specified tiered sell rate",      "$/kW",   "",                      "",             "ur_tr_sell_type=0",         "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p1_energy_ub1",      "Tiered Struct. 1 Energy UB 1",    "kWh",    "",                      "",             "?=1e99",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p1_energy_ub2",      "Tiered Struct. 1 Energy UB 2",    "kWh",    "",                      "",             "?=1e99",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p1_energy_ub3",      "Tiered Struct. 1 Energy UB 3",    "kWh",    "",                      "",             "?=1e99",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p1_energy_ub4",      "Tiered Struct. 1 Energy UB 4",    "kWh",    "",                      "",             "?=1e99",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p1_energy_ub5",      "Tiered Struct. 1 Energy UB 5",    "kWh",    "",                      "",             "?=1e99",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p1_energy_ub6",      "Tiered Struct. 1 Energy UB 6",    "kWh",    "",                      "",             "?=1e99",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p1_rate1",           "Tiered Struct. 1 Rate 1",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p1_rate2",           "Tiered Struct. 1 Rate 2",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p1_rate3",           "Tiered Struct. 1 Rate 3",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p1_rate4",           "Tiered Struct. 1 Rate 4",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p1_rate5",           "Tiered Struct. 1 Rate 5",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p1_rate6",           "Tiered Struct. 1 Rate 6",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p2_energy_ub1",      "Tiered Struct. 2 Energy UB 1",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p2_energy_ub2",      "Tiered Struct. 2 Energy UB 2",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p2_energy_ub3",      "Tiered Struct. 2 Energy UB 3",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p2_energy_ub4",      "Tiered Struct. 2 Energy UB 4",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p2_energy_ub5",      "Tiered Struct. 2 Energy UB 5",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p2_energy_ub6",      "Tiered Struct. 2 Energy UB 6",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p2_rate1",           "Tiered Struct. 2 Rate 1",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p2_rate2",           "Tiered Struct. 2 Rate 2",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p2_rate3",           "Tiered Struct. 2 Rate 3",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p2_rate4",           "Tiered Struct. 2 Rate 4",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p2_rate5",           "Tiered Struct. 2 Rate 5",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p2_rate6",           "Tiered Struct. 2 Rate 6",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p3_energy_ub1",      "Tiered Struct. 3 Energy UB 1",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p3_energy_ub2",      "Tiered Struct. 3 Energy UB 2",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p3_energy_ub3",      "Tiered Struct. 3 Energy UB 3",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p3_energy_ub4",      "Tiered Struct. 3 Energy UB 4",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p3_energy_ub5",      "Tiered Struct. 3 Energy UB 5",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p3_energy_ub6",      "Tiered Struct. 3 Energy UB 6",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p3_rate1",           "Tiered Struct. 3 Rate 1",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p3_rate2",           "Tiered Struct. 3 Rate 2",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p3_rate3",           "Tiered Struct. 3 Rate 3",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p3_rate4",           "Tiered Struct. 3 Rate 4",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p3_rate5",           "Tiered Struct. 3 Rate 5",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p3_rate6",           "Tiered Struct. 3 Rate 6",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p4_energy_ub1",      "Tiered Struct. 4 Energy UB 1",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p4_energy_ub2",      "Tiered Struct. 4 Energy UB 2",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p4_energy_ub3",      "Tiered Struct. 4 Energy UB 3",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p4_energy_ub4",      "Tiered Struct. 4 Energy UB 4",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p4_energy_ub5",      "Tiered Struct. 4 Energy UB 5",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p4_energy_ub6",      "Tiered Struct. 4 Energy UB 6",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p4_rate1",           "Tiered Struct. 4 Rate 1",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p4_rate2",           "Tiered Struct. 4 Rate 2",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p4_rate3",           "Tiered Struct. 4 Rate 3",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p4_rate4",           "Tiered Struct. 4 Rate 4",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p4_rate5",           "Tiered Struct. 4 Rate 5",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p4_rate6",           "Tiered Struct. 4 Rate 6",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p5_energy_ub1",      "Tiered Struct. 5 Energy UB 1",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p5_energy_ub2",      "Tiered Struct. 5 Energy UB 2",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p5_energy_ub3",      "Tiered Struct. 5 Energy UB 3",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p5_energy_ub4",      "Tiered Struct. 5 Energy UB 4",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p5_energy_ub5",      "Tiered Struct. 5 Energy UB 5",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p5_energy_ub6",      "Tiered Struct. 5 Energy UB 6",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p5_rate1",           "Tiered Struct. 5 Rate 1",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p5_rate2",           "Tiered Struct. 5 Rate 2",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p5_rate3",           "Tiered Struct. 5 Rate 3",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p5_rate4",           "Tiered Struct. 5 Rate 4",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p5_rate5",           "Tiered Struct. 5 Rate 5",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p5_rate6",           "Tiered Struct. 5 Rate 6",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p6_energy_ub1",      "Tiered Struct. 6 Energy UB 1",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p6_energy_ub2",      "Tiered Struct. 6 Energy UB 2",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p6_energy_ub3",      "Tiered Struct. 6 Energy UB 3",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p6_energy_ub4",      "Tiered Struct. 6 Energy UB 4",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p6_energy_ub5",      "Tiered Struct. 6 Energy UB 5",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p6_energy_ub6",      "Tiered Struct. 6 Energy UB 6",    "kWh",    "",                      "",             "?=1e99",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p6_rate1",           "Tiered Struct. 6 Rate 1",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p6_rate2",           "Tiered Struct. 6 Rate 2",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p6_rate3",           "Tiered Struct. 6 Rate 3",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p6_rate4",           "Tiered Struct. 6 Rate 4",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p6_rate5",           "Tiered Struct. 6 Rate 5",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_p6_rate6",           "Tiered Struct. 6 Rate 6",         "$/kWh",  "",                      "",             "?=0.0",                     "",                              "" },

	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_sched_m1",           "Tiered Structure for January",    "0-5",    "tiered structure #",    "",             "?=0",                       "INTEGER,MIN=0,MAX=5",           "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_sched_m2",           "Tiered Structure for February"    "0-5",    "tiered structure #",    "",             "?=0",                       "INTEGER,MIN=0,MAX=5",           "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_sched_m3",           "Tiered Structure for March",      "0-5",    "tiered structure #",    "",             "?=0",                       "INTEGER,MIN=0,MAX=5",           "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_sched_m4",           "Tiered Structure for April",      "0-5",    "tiered structure #",    "",             "?=0",                       "INTEGER,MIN=0,MAX=5",           "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_sched_m5",           "Tiered Structure for May",        "0-5",    "tiered structure #",    "",             "?=0",                       "INTEGER,MIN=0,MAX=5",           "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_sched_m6",           "Tiered Structure for June",       "0-5",    "tiered structure #",    "",             "?=0",                       "INTEGER,MIN=0,MAX=5",           "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_sched_m7",           "Tiered Structure for July",       "0-5",    "tiered structure #",    "",             "?=0",                       "INTEGER,MIN=0,MAX=5",           "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_sched_m8",           "Tiered Structure for August",     "0-5",    "tiered structure #",    "",             "?=0",                       "INTEGER,MIN=0,MAX=5",           "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_sched_m9",           "Tiered Structure for September",  "0-5",    "tiered structure #",    "",             "?=0",                       "INTEGER,MIN=0,MAX=5",           "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_sched_m10",          "Tiered Structure for October",    "0-5",    "tiered structure #",    "",             "?=0",                       "INTEGER,MIN=0,MAX=5",           "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_sched_m11",          "Tiered Structure for November",   "0-5",    "tiered structure #",    "",             "?=0",                       "INTEGER,MIN=0,MAX=5",           "" },
	{ SSC_INPUT,        SSC_NUMBER,     "ur_tr_sched_m12",          "Tiered Structure for December",   "0-5",    "tiered structure #",    "",             "?=0",                       "INTEGER,MIN=0,MAX=5",           "" },
	
var_info_invalid };
	
var_info vtab_tax_credits[] = {
/*   VARTYPE           DATATYPE         NAME                               LABEL                                                UNITS     META                      GROUP                 REQUIRED_IF                 CONSTRAINTS                      UI_HINTS*/

	{ SSC_INPUT,        SSC_ARRAY,       "itc_fed_amount",                 "Federal Amount-based ITC Amount",                         "$",      "",          "Tax Credit Incentives",      "?=0",                       "",                            "" },
	{ SSC_INPUT,        SSC_NUMBER,      "itc_fed_amount_deprbas_fed",     "Federal Amount-based ITC Reduces Fed. Depr. Basis",       "0/1",    "",          "Tax Credit Incentives",      "?=1",                       "BOOLEAN",                     "" },
	{ SSC_INPUT,        SSC_NUMBER,      "itc_fed_amount_deprbas_sta",     "Federal Amount-based ITC Reduces Sta. Depr. Basis",       "0/1",    "",          "Tax Credit Incentives",      "?=1",                       "BOOLEAN",                     "" },
	
	{ SSC_INPUT,        SSC_ARRAY,       "itc_sta_amount",                 "State Amount-based ITC Amount",                           "$",      "",          "Tax Credit Incentives",      "?=0",                       "",                            "" },
	{ SSC_INPUT,        SSC_NUMBER,      "itc_sta_amount_deprbas_fed",     "State Amount-based ITC Reduces Fed. Depr. Basis",         "0/1",    "",          "Tax Credit Incentives",      "?=0",                       "BOOLEAN",                     "" },
	{ SSC_INPUT,        SSC_NUMBER,      "itc_sta_amount_deprbas_sta",     "State Amount-based ITC Reduces Sta. Depr. Basis",         "0/1",    "",          "Tax Credit Incentives",      "?=0",                       "BOOLEAN",                     "" },
	
	{ SSC_INPUT,        SSC_ARRAY,       "itc_fed_percent",                "Federal Percentage-based ITC Percent",                    "%",      "",          "Tax Credit Incentives",      "?=0",                       "",                            "" },
	{ SSC_INPUT,        SSC_NUMBER,      "itc_fed_percent_maxvalue",       "Federal Percentage-based ITC Max. Value",                 "$",      "",          "Tax Credit Incentives",      "?=1e99",                    "",                            "" },
	{ SSC_INPUT,        SSC_NUMBER,      "itc_fed_percent_deprbas_fed",    "Federal Percentage-based ITC Reduces Fed. Depr. Basis",   "0/1",    "",          "Tax Credit Incentives",      "?=1",                       "BOOLEAN",                     "" },
	{ SSC_INPUT,        SSC_NUMBER,      "itc_fed_percent_deprbas_sta",    "Federal Percentage-based ITC Reduces Sta. Depr. Basis",   "0/1",    "",          "Tax Credit Incentives",      "?=1",                       "BOOLEAN",                     "" },

	{ SSC_INPUT,        SSC_ARRAY,       "itc_sta_percent",                "State Percentage-based ITC Percent",                      "%",      "",          "Tax Credit Incentives",      "?=0",                       "",                            "" },
	{ SSC_INPUT,        SSC_NUMBER,      "itc_sta_percent_maxvalue",       "State Percentage-based ITC Max. Value",                   "$",      "",          "Tax Credit Incentives",      "?=1e99",                    "",                            "" },
	{ SSC_INPUT,        SSC_NUMBER,      "itc_sta_percent_deprbas_fed",    "State Percentage-based ITC Reduces Fed. Depr. Basis",     "0/1",    "",          "Tax Credit Incentives",      "?=0",                       "BOOLEAN",                     "" },
	{ SSC_INPUT,        SSC_NUMBER,      "itc_sta_percent_deprbas_sta",    "State Percentage-based ITC Reduces Sta. Depr. Basis",     "0/1",    "",          "Tax Credit Incentives",      "?=0",                       "BOOLEAN",                     "" },

	{ SSC_INPUT,        SSC_ARRAY,       "ptc_fed_amount",                 "Federal PTC Amount",                                      "$/kWh",  "",          "Tax Credit Incentives",      "?=0",                       "",                            "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ptc_fed_term",                   "Federal PTC Term",                                        "years",  "",          "Tax Credit Incentives",      "?=10",                      "",                            "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ptc_fed_escal",                  "Federal PTC Escalation",                                  "%/year", "",          "Tax Credit Incentives",      "?=0",                       "",                            "" },
	
	{ SSC_INPUT,        SSC_ARRAY,       "ptc_sta_amount",                 "State PTC Amount",                                        "$/kWh",  "",          "Tax Credit Incentives",      "?=0",                       "",                            "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ptc_sta_term",                   "State PTC Term",                                          "years",  "",          "Tax Credit Incentives",      "?=10",                      "",                            "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ptc_sta_escal",                  "State PTC Escalation",                                    "%/year", "",          "Tax Credit Incentives",      "?=0",                       "",                            "" },
	
var_info_invalid };
	
var_info vtab_payment_incentives[] = {
	/*   VARTYPE           DATATYPE         NAME                          LABEL                                                  UNITS     META                      GROUP                   REQUIRED_IF                 CONSTRAINTS                      UI_HINTS*/

	{ SSC_INPUT,        SSC_ARRAY,       "ibi_fed_amount",                "Federal Amount-based IBI Amount",                    "$",      "",                      "Payment Incentives",      "?=0",                 "",                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_fed_amount_tax_fed",        "Federal Amount-based IBI Fed. Taxable",              "0/1",    "",                      "Payment Incentives",      "?=1",                 "BOOLEAN",                       "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_fed_amount_tax_sta",        "Federal Amount-based IBI Sta. Taxable",              "0/1",    "",                      "Payment Incentives",      "?=1",                 "BOOLEAN",                       "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_fed_amount_itcbas_fed",     "Federal Amount-based IBI Reduces Fed. ITC Basis",    "0/1",    "",                      "Payment Incentives",      "?=0",                 "BOOLEAN",                       "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_fed_amount_itcbas_sta",     "Federal Amount-based IBI Reduces Sta. ITC Basis",    "0/1",    "",                      "Payment Incentives",      "?=0",                 "BOOLEAN",                       "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_fed_amount_deprbas_fed",    "Federal Amount-based IBI Reduces Fed. Depr. Basis",  "0/1",    "",                      "Payment Incentives",      "?=0",                 "BOOLEAN",                       "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_fed_amount_deprbas_sta",    "Federal Amount-based IBI Reduces Sta. Depr. Basis",  "0/1",    "",                      "Payment Incentives",      "?=0",                 "BOOLEAN",                       "" },
	
	{ SSC_INPUT,        SSC_ARRAY,       "ibi_sta_amount",                "State Amount-based IBI Amount",                    "$",      "",                      "Payment Incentives",      "?=0",                   "",                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_sta_amount_tax_fed",        "State Amount-based IBI Fed. Taxable",              "0/1",    "",                      "Payment Incentives",      "?=1",                   "BOOLEAN",                       "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_sta_amount_tax_sta",        "State Amount-based IBI Sta. Taxable",              "0/1",    "",                      "Payment Incentives",      "?=1",                   "BOOLEAN",                       "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_sta_amount_itcbas_fed",     "State Amount-based IBI Reduces Fed. ITC Basis",    "0/1",    "",                      "Payment Incentives",      "?=0",                   "BOOLEAN",                       "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_sta_amount_itcbas_sta",     "State Amount-based IBI Reduces Sta. ITC Basis",    "0/1",    "",                      "Payment Incentives",      "?=0",                   "BOOLEAN",                       "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_sta_amount_deprbas_fed",    "State Amount-based IBI Reduces Fed. Depr. Basis",  "0/1",    "",                      "Payment Incentives",      "?=0",                   "BOOLEAN",                       "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_sta_amount_deprbas_sta",    "State Amount-based IBI Reduces Sta. Depr. Basis",  "0/1",    "",                      "Payment Incentives",      "?=0",                   "BOOLEAN",                       "" },
	
	{ SSC_INPUT,        SSC_ARRAY,       "ibi_uti_amount",                "Utility Amount-based IBI Amount",                    "$",      "",                      "Payment Incentives",      "?=0",                 "",                      "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_uti_amount_tax_fed",        "Utility Amount-based IBI Fed. Taxable",              "0/1",    "",                      "Payment Incentives",      "?=1",                 "BOOLEAN",                       "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_uti_amount_tax_sta",        "Utility Amount-based IBI Sta. Taxable",              "0/1",    "",                      "Payment Incentives",      "?=1",                 "BOOLEAN",                       "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_uti_amount_itcbas_fed",     "Utility Amount-based IBI Reduces Fed. ITC Basis",    "0/1",    "",                      "Payment Incentives",      "?=0",                 "BOOLEAN",                       "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_uti_amount_itcbas_sta",     "Utility Amount-based IBI Reduces Sta. ITC Basis",    "0/1",    "",                      "Payment Incentives",      "?=0",                 "BOOLEAN",                       "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_uti_amount_deprbas_fed",    "Utility Amount-based IBI Reduces Fed. Depr. Basis",  "0/1",    "",                      "Payment Incentives",      "?=0",                 "BOOLEAN",                       "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_uti_amount_deprbas_sta",    "Utility Amount-based IBI Reduces Sta. Depr. Basis",  "0/1",    "",                      "Payment Incentives",      "?=0",                 "BOOLEAN",                       "" },
	
	{ SSC_INPUT,        SSC_ARRAY,       "ibi_oth_amount",                "Other Amount-based IBI Amount",                    "$",      "",                      "Payment Incentives",      "?=0",                   "",                      "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_oth_amount_tax_fed",        "Other Amount-based IBI Fed. Taxable",              "0/1",    "",                      "Payment Incentives",      "?=1",                   "BOOLEAN",                       "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_oth_amount_tax_sta",        "Other Amount-based IBI Sta. Taxable",              "0/1",    "",                      "Payment Incentives",      "?=1",                   "BOOLEAN",                       "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_oth_amount_itcbas_fed",     "Other Amount-based IBI Reduces Fed. ITC Basis",    "0/1",    "",                      "Payment Incentives",      "?=0",                   "BOOLEAN",                       "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_oth_amount_itcbas_sta",     "Other Amount-based IBI Reduces Sta. ITC Basis",    "0/1",    "",                      "Payment Incentives",      "?=0",                   "BOOLEAN",                       "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_oth_amount_deprbas_fed",    "Other Amount-based IBI Reduces Fed. Depr. Basis",  "0/1",    "",                      "Payment Incentives",      "?=0",                   "BOOLEAN",                       "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_oth_amount_deprbas_sta",    "Other Amount-based IBI Reduces Sta. Depr. Basis",  "0/1",    "",                      "Payment Incentives",      "?=0",                   "BOOLEAN",                       "" },

	{ SSC_INPUT,        SSC_ARRAY,       "ibi_fed_percent",               "Federal Percentage-based IBI Percent",                   "%",      "",                      "Payment Incentives",      "?=0.0",           "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_fed_percent_maxvalue",      "Federal Percentage-based IBI Maximum Value",             "$",      "",                      "Payment Incentives",      "?=1e99",          "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_fed_percent_tax_fed",       "Federal Percentage-based IBI Fed. Taxable",              "0/1",    "",                      "Payment Incentives",      "?=1",             "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_fed_percent_tax_sta",       "Federal Percentage-based IBI Sta. Taxable",              "0/1",    "",                      "Payment Incentives",      "?=1",             "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_fed_percent_itcbas_fed",    "Federal Percentage-based IBI Reduces Fed. ITC Basis",    "0/1",    "",                      "Payment Incentives",      "?=0",             "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_fed_percent_itcbas_sta",    "Federal Percentage-based IBI Reduces Sta. ITC Basis",    "0/1",    "",                      "Payment Incentives",      "?=0",             "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_fed_percent_deprbas_fed",   "Federal Percentage-based IBI Reduces Fed. Depr. Basis",  "0/1",    "",                      "Payment Incentives",      "?=0",             "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_fed_percent_deprbas_sta",   "Federal Percentage-based IBI Reduces Sta. Depr. Basis",  "0/1",    "",                      "Payment Incentives",      "?=0",             "BOOLEAN",                                         "" },

	{ SSC_INPUT,        SSC_ARRAY,       "ibi_sta_percent",               "State Percentage-based IBI Percent",                   "%",      "",                      "Payment Incentives",      "?=0.0",           "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_sta_percent_maxvalue",      "State Percentage-based IBI Maximum Value",             "$",      "",                      "Payment Incentives",      "?=1e99",          "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_sta_percent_tax_fed",       "State Percentage-based IBI Fed. Taxable",              "0/1",    "",                      "Payment Incentives",      "?=1",             "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_sta_percent_tax_sta",       "State Percentage-based IBI Sta. Taxable",              "0/1",    "",                      "Payment Incentives",      "?=1",             "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_sta_percent_itcbas_fed",    "State Percentage-based IBI Reduces Fed. ITC Basis",    "0/1",    "",                      "Payment Incentives",      "?=0",             "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_sta_percent_itcbas_sta",    "State Percentage-based IBI Reduces Sta. ITC Basis",    "0/1",    "",                      "Payment Incentives",      "?=0",             "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_sta_percent_deprbas_fed",   "State Percentage-based IBI Reduces Fed. Depr. Basis",  "0/1",    "",                      "Payment Incentives",      "?=0",             "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_sta_percent_deprbas_sta",   "State Percentage-based IBI Reduces Sta. Depr. Basis",  "0/1",    "",                      "Payment Incentives",      "?=0",             "BOOLEAN",                                         "" },

	{ SSC_INPUT,        SSC_ARRAY,       "ibi_uti_percent",               "Utility Percentage-based IBI Percent",                   "%",      "",                      "Payment Incentives",      "?=0.0",           "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_uti_percent_maxvalue",      "Utility Percentage-based IBI Maximum Value",             "$",      "",                      "Payment Incentives",      "?=1e99",          "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_uti_percent_tax_fed",       "Utility Percentage-based IBI Fed. Taxable",              "0/1",    "",                      "Payment Incentives",      "?=1",             "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_uti_percent_tax_sta",       "Utility Percentage-based IBI Sta. Taxable",              "0/1",    "",                      "Payment Incentives",      "?=1",             "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_uti_percent_itcbas_fed",    "Utility Percentage-based IBI Reduces Fed. ITC Basis",    "0/1",    "",                      "Payment Incentives",      "?=0",             "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_uti_percent_itcbas_sta",    "Utility Percentage-based IBI Reduces Sta. ITC Basis",    "0/1",    "",                      "Payment Incentives",      "?=0",             "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_uti_percent_deprbas_fed",   "Utility Percentage-based IBI Reduces Fed. Depr. Basis",  "0/1",    "",                      "Payment Incentives",      "?=0",             "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_uti_percent_deprbas_sta",   "Utility Percentage-based IBI Reduces Sta. Depr. Basis",  "0/1",    "",                      "Payment Incentives",      "?=0",             "BOOLEAN",                                         "" },

	{ SSC_INPUT,        SSC_ARRAY,       "ibi_oth_percent",               "Other Percentage-based IBI Percent",                   "%",      "",                      "Payment Incentives",      "?=0.0",           "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_oth_percent_maxvalue",      "Other Percentage-based IBI Maximum Value",             "$",      "",                      "Payment Incentives",      "?=1e99",          "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_oth_percent_tax_fed",       "Other Percentage-based IBI Fed. Taxable",              "0/1",    "",                      "Payment Incentives",      "?=1",             "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_oth_percent_tax_sta",       "Other Percentage-based IBI Sta. Taxable",              "0/1",    "",                      "Payment Incentives",      "?=1",             "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_oth_percent_itcbas_fed",    "Other Percentage-based IBI Reduces Fed. ITC Basis",    "0/1",    "",                      "Payment Incentives",      "?=0",             "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_oth_percent_itcbas_sta",    "Other Percentage-based IBI Reduces Sta. ITC Basis",    "0/1",    "",                      "Payment Incentives",      "?=0",             "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_oth_percent_deprbas_fed",   "Other Percentage-based IBI Reduces Fed. Depr. Basis",  "0/1",    "",                      "Payment Incentives",      "?=0",             "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ibi_oth_percent_deprbas_sta",   "Other Percentage-based IBI Reduces Sta. Depr. Basis",  "0/1",    "",                      "Payment Incentives",      "?=0",             "BOOLEAN",                                         "" },


	{ SSC_INPUT,        SSC_ARRAY,       "cbi_fed_amount",                "Federal CBI Amount",                   "$/Watt", "",                      "Payment Incentives",      "?=0.0",                     "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_fed_amount_max",            "Federal CBI Maximum",                  "$",      "",                      "Payment Incentives",      "?=1e99",                    "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_fed_amount_tax_fed",        "Federal CBI Fed. Taxable",             "0/1",    "",                      "Payment Incentives",      "?=1",                       "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_fed_amount_tax_sta",        "Federal CBI Sta. Taxable",             "0/1",    "",                      "Payment Incentives",      "?=1",                       "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_fed_amount_itcbas_fed",     "Federal CBI Reduces Fed. ITC Basis",   "0/1",    "",                      "Payment Incentives",      "?=0",                       "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_fed_amount_itcbas_sta",     "Federal CBI Reduces Sta. ITC Basis",   "0/1",    "",                      "Payment Incentives",      "?=0",                       "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_fed_amount_deprbas_fed",    "Federal CBI Reduces Fed. Depr. Basis", "0/1",    "",                      "Payment Incentives",      "?=0",                       "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_fed_amount_deprbas_sta",    "Federal CBI Reduces Sta. Depr. Basis", "0/1",    "",                      "Payment Incentives",      "?=0",                       "BOOLEAN",                                         "" },
	
	{ SSC_INPUT,        SSC_ARRAY,       "cbi_sta_amount",                "State CBI Amount",                   "$/Watt", "",                      "Payment Incentives",      "?=0.0",                     "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_sta_amount_max",            "State CBI Maximum",                  "$",      "",                      "Payment Incentives",      "?=1e99",                    "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_sta_amount_tax_fed",        "State CBI Fed. Taxable",             "0/1",    "",                      "Payment Incentives",      "?=1",                       "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_sta_amount_tax_sta",        "State CBI Sta. Taxable",             "0/1",    "",                      "Payment Incentives",      "?=1",                       "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_sta_amount_itcbas_fed",     "State CBI Reduces Fed. ITC Basis",   "0/1",    "",                      "Payment Incentives",      "?=0",                       "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_sta_amount_itcbas_sta",     "State CBI Reduces Sta. ITC Basis",   "0/1",    "",                      "Payment Incentives",      "?=0",                       "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_sta_amount_deprbas_fed",    "State CBI Reduces Fed. Depr. Basis", "0/1",    "",                      "Payment Incentives",      "?=0",                       "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_sta_amount_deprbas_sta",    "State CBI Reduces Sta. Depr. Basis", "0/1",    "",                      "Payment Incentives",      "?=0",                       "BOOLEAN",                                         "" },
	
	{ SSC_INPUT,        SSC_ARRAY,       "cbi_uti_amount",                "Utility CBI Amount",                   "$/Watt", "",                      "Payment Incentives",      "?=0.0",                     "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_uti_amount_max",            "Utility CBI Maximum",                  "$",      "",                      "Payment Incentives",      "?=1e99",                    "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_uti_amount_tax_fed",        "Utility CBI Fed. Taxable",             "0/1",    "",                      "Payment Incentives",      "?=1",                       "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_uti_amount_tax_sta",        "Utility CBI Sta. Taxable",             "0/1",    "",                      "Payment Incentives",      "?=1",                       "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_uti_amount_itcbas_fed",     "Utility CBI Reduces Fed. ITC Basis",   "0/1",    "",                      "Payment Incentives",      "?=0",                       "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_uti_amount_itcbas_sta",     "Utility CBI Reduces Sta. ITC Basis",   "0/1",    "",                      "Payment Incentives",      "?=0",                       "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_uti_amount_deprbas_fed",    "Utility CBI Reduces Fed. Depr. Basis", "0/1",    "",                      "Payment Incentives",      "?=0",                       "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_uti_amount_deprbas_sta",    "Utility CBI Reduces Sta. Depr. Basis", "0/1",    "",                      "Payment Incentives",      "?=0",                       "BOOLEAN",                                         "" },
	
	{ SSC_INPUT,        SSC_ARRAY,       "cbi_oth_amount",                "Other CBI Amount",                   "$/Watt", "",                      "Payment Incentives",      "?=0.0",                     "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_oth_amount_max",            "Other CBI Maximum",                  "$",      "",                      "Payment Incentives",      "?=1e99",                    "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_oth_amount_tax_fed",        "Other CBI Fed. Taxable",             "0/1",    "",                      "Payment Incentives",      "?=1",                       "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_oth_amount_tax_sta",        "Other CBI Sta. Taxable",             "0/1",    "",                      "Payment Incentives",      "?=1",                       "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_oth_amount_itcbas_fed",     "Other CBI Reduces Fed. ITC Basis",   "0/1",    "",                      "Payment Incentives",      "?=0",                       "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_oth_amount_itcbas_sta",     "Other CBI Reduces Sta. ITC Basis",   "0/1",    "",                      "Payment Incentives",      "?=0",                       "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_oth_amount_deprbas_fed",    "Other CBI Reduces Fed. Depr. Basis", "0/1",    "",                      "Payment Incentives",      "?=0",                       "BOOLEAN",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cbi_oth_amount_deprbas_sta",    "Other CBI Reduces Sta. Depr. Basis", "0/1",    "",                      "Payment Incentives",      "?=0",                       "BOOLEAN",                                         "" },


	{ SSC_INPUT,        SSC_ARRAY,       "pbi_fed_amount",                "Federal PBI Amount",           "%/kWh",    "",                      "Payment Incentives",      "?=0",                       "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "pbi_fed_term",                  "Federal PBI Term",             "years",    "",                      "Payment Incentives",      "?=0",                       "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "pbi_fed_escal",                 "Federal PBI Escalation",       "%",        "",                      "Payment Incentives",      "?=0",                       "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "pbi_fed_tax_fed",               "Federal PBI Fed. Taxable",     "0/1",      "",                      "Payment Incentives",      "?=1",                       "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "pbi_fed_tax_sta",               "Federal PBI Sta. Taxable",     "0/1",      "",                      "Payment Incentives",      "?=1",                       "",                                         "" },
	
	{ SSC_INPUT,        SSC_ARRAY,       "pbi_sta_amount",                "State PBI Amount",           "%/kWh",    "",                      "Payment Incentives",      "?=0",                       "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "pbi_sta_term",                  "State PBI Term",             "years",    "",                      "Payment Incentives",      "?=0",                       "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "pbi_sta_escal",                 "State PBI Escalation",       "%",        "",                      "Payment Incentives",      "?=0",                       "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "pbi_sta_tax_fed",               "State PBI Fed. Taxable",     "0/1",      "",                      "Payment Incentives",      "?=1",                       "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "pbi_sta_tax_sta",               "State PBI Sta. Taxable",     "0/1",      "",                      "Payment Incentives",      "?=1",                       "",                                         "" },
	
	{ SSC_INPUT,        SSC_ARRAY,       "pbi_uti_amount",                "Utility PBI Amount",           "%/kWh",    "",                      "Payment Incentives",      "?=0",                       "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "pbi_uti_term",                  "Utility PBI Term",             "years",    "",                      "Payment Incentives",      "?=0",                       "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "pbi_uti_escal",                 "Utility PBI Escalation",       "%",        "",                      "Payment Incentives",      "?=0",                       "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "pbi_uti_tax_fed",               "Utility PBI Fed. Taxable",     "0/1",      "",                      "Payment Incentives",      "?=1",                       "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "pbi_uti_tax_sta",               "Utility PBI Sta. Taxable",     "0/1",      "",                      "Payment Incentives",      "?=1",                       "",                                         "" },
	
	{ SSC_INPUT,        SSC_ARRAY,       "pbi_oth_amount",                "Other PBI Amount",           "%/kWh",    "",                      "Payment Incentives",      "?=0",                       "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "pbi_oth_term",                  "Other PBI Term",             "years",    "",                      "Payment Incentives",      "?=0",                       "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "pbi_oth_escal",                 "Other PBI Escalation",       "%",        "",                      "Payment Incentives",      "?=0",                       "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "pbi_oth_tax_fed",               "Other PBI Fed. Taxable",     "0/1",      "",                      "Payment Incentives",      "?=1",                       "",                                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "pbi_oth_tax_sta",               "Other PBI Sta. Taxable",     "0/1",      "",                      "Payment Incentives",      "?=1",                       "",                                         "" },

var_info_invalid };
