/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface sscapiConstants {
  public final static int SSC_INVALID = sscapiJNI.SSC_INVALID_get();
  public final static int SSC_STRING = sscapiJNI.SSC_STRING_get();
  public final static int SSC_NUMBER = sscapiJNI.SSC_NUMBER_get();
  public final static int SSC_ARRAY = sscapiJNI.SSC_ARRAY_get();
  public final static int SSC_MATRIX = sscapiJNI.SSC_MATRIX_get();
  public final static int SSC_TABLE = sscapiJNI.SSC_TABLE_get();
  public final static int SSC_INPUT = sscapiJNI.SSC_INPUT_get();
  public final static int SSC_OUTPUT = sscapiJNI.SSC_OUTPUT_get();
  public final static int SSC_INOUT = sscapiJNI.SSC_INOUT_get();
  public final static int SSC_LOG = sscapiJNI.SSC_LOG_get();
  public final static int SSC_UPDATE = sscapiJNI.SSC_UPDATE_get();
  public final static int SSC_EXECUTE = sscapiJNI.SSC_EXECUTE_get();
  public final static int SSC_NOTICE = sscapiJNI.SSC_NOTICE_get();
  public final static int SSC_WARNING = sscapiJNI.SSC_WARNING_get();
  public final static int SSC_ERROR = sscapiJNI.SSC_ERROR_get();
}
