#include "cmod_trnbase.h"

static var_info _cm_vtab_trntower[] = {
/*   VARTYPE           DATATYPE         NAME                                            LABEL                                                    UNITS      META                                    GROUP                  REQUIRED_IF                 CONSTRAINTS                      UI_HINTS*/
	{ SSC_INPUT,        SSC_STRING,      "weather_file",                                "Weather data file (TM2,TM2,EPW)",                       "",       "",                      "Dish Stirling",       "*",                    "",                              "" },

	{ SSC_INPUT,        SSC_NUMBER,      "solar_multiple",           "Solar multiple",                    "",       "",                      "PTFlux",      "*",                         "POSITIVE",                 "" },
	{ SSC_INPUT,        SSC_NUMBER,      "span_angle",               "Field span angle",                  "deg",    "",                      "PTFlux",      "*",                         "MIN=0,MAX=360",            "" },

	{ SSC_INPUT,        SSC_MATRIX,      "heliostat_field",          "Heliostat field matrix",            "",       "",                      "PTFlux",      "*",                         "",                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "round_heliostats",         "Use round heliostats",              "0/1",    "",                      "PTFlux",      "*",                         "BOOLEAN",                  "" },
	{ SSC_INPUT,        SSC_NUMBER,      "heliostat_width",          "Heliostat width",                   "m",      "",                      "PTFlux",      "*",                         "",                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "heliostat_height",         "Heliostat height",                  "m",      "",                      "PTFlux",      "*",                         "",                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "field_availability",       "Heliostat field availability",      "%",      "",                      "PTFlux",      "*",                         "MIN=0,MAX=100",            "" },
	{ SSC_INPUT,        SSC_NUMBER,      "ratio_reflect_to_profile", "Ratio reflected area to profile",   "frac",   "",                      "PTFlux",      "*",                         "MIN=0,MAX=1",              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "mirror_reflectivity",      "Mirror reflectivity",               "frac",   "",                      "PTFlux",      "*",                         "MIN=0,MAX=1",              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "max_hel_tower_dist_ratio", "Max helio-to-tower distance ratio", "frac", "",                        "PTFlux",      "*",                         "POSITIVE",                 "" },
	{ SSC_INPUT,        SSC_NUMBER,      "min_hel_tower_dist_ratio", "Min helio-to-tower distance ratio", "frac", "",                        "PTFlux",      "*",                         "POSITIVE",                 "" },
	{ SSC_INPUT,        SSC_NUMBER,      "image_error",              "Image error",                       "rad",    "",                      "PTFlux",      "*",                         "",                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "coating_absorptivity",     "Coating absorptivity",              "frac",   "",                      "PTFlux",      "*",                         "MIN=0,MAX=1",              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "max_receiver_flux",        "Max receiver flux",                 "kWt/m2", "",                      "PTFlux",      "*",                         "",                         "" },
	
	{ SSC_INPUT,        SSC_NUMBER,      "receiver_type",            "Receiver type",                     "",       "0=external,1=cavity",   "PTFlux",      "*",                         "MIN=0,MAX=1,INTEGER",      "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cavity_aperture_width",    "Cavity aperture width",             "m",      "",                      "PTFlux",      "receiver_type=1",           "",                         "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cavity_aperture_hw_ratio", "Cavity height-to-width ratio",      "frac",   "",                      "PTFlux",      "receiver_type=1",           "MIN=0,MAX=1",              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cavity_lip_height_ratio",  "Cavity lip-to-height ratio",        "frac",   "",                      "PTFlux",      "receiver_type=1",           "MIN=0,MAX=1",              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "exter_height",             "External receiver height",          "m",      "",                      "PTFlux",      "receiver_type=0",           "POSITIVE",                 "" },
	{ SSC_INPUT,        SSC_NUMBER,      "exter_diameter",           "External receiver diameter",        "m",      "",                      "PTFlux",      "receiver_type=0",           "POSITIVE"                  "" },
	{ SSC_INPUT,        SSC_NUMBER,      "tower_height",             "Tower height",                      "m",      "",                      "PTFlux",      "*",                         "MIN=0",                    "" },
	{ SSC_INPUT,        SSC_NUMBER,      "design_gross_capacity",    "Plant gross capacity",              "MW",     "",                      "PTFlux",      "*",                         "MIN=0",                    "" },
	{ SSC_INPUT,        SSC_NUMBER,      "cycle_eff",                "Cycle efficiency",                  "frac",   "",                      "PTFlux",      "*",                         "MIN=0",                    "" },

	{ SSC_INPUT,        SSC_MATRIX,      "optieff_matrix",           "Optical efficiency matrix",         "",    "",                         "PTFlux",      "*",                         "",                         "" },
	{ SSC_INPUT,        SSC_ARRAY,       "optieff_azimuth",          "Efficiency array azimuth angles"    "",    "",                         "PTFlux",      "*",                         "",                         "" },
	{ SSC_INPUT,        SSC_ARRAY,       "optieff_zenith",           "Efficiency array zenith angles"     "",    "",                         "PTFlux",      "*",                         "",                         "" },

	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.sf.wind_stow_speed",                   "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.sf.stow_deploy_angle",                 "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.sf.water_usage_per_wash",              "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.sf.washing_frequency",                 "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.sf.total_reflective_area",             "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.rec.cav_panel_height",                 "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.rec.ext_num_panels",                   "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.rec.tube_outer_diameter",              "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.rec.tube_wall_thickness",              "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.rec.material_type",                    "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.rec.flow_pattern",                     "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.rec.req_htf_outlet_temp",              "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.rec.max_temp_to_rec",                  "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.rec.max_flow_to_rec",                  "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.rec.ext_coating_emissivity",            "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.rec.enable_night_recirc",              "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.rec.recirc_eff",                       "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.rec.htf_type",                         "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_ARRAY,       "csp.pt.rec.custom_htf",                       "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.rec.design_thermal_power",             "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.rec.min_turndown_frac",                "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.rec.startup_delay_time",               "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.rec.startup_delay_energy_frac",            "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.rec.heat_loss_f",                      "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.boiler_steam_pressure",            "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.cycle_eff",                       "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.design_ambient_temp",             "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.design_htf_inlet_temp",            "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.design_htf_outlet_temp",            "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.design_thermal_power",            "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.max_over_design",                 "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.min_load",                        "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.min_temp_to_load",                "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.design_gross_output",             "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.ref_condenser_dt",                "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.standby_fraction",                "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.standby_period",                  "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.startup_fraction",                "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.startup_time",                    "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.lhv_eff",                         "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.blowdown_frac",                   "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.approach_temp",                   "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.condenser_pressure_ratio",            "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.condenser_type",                  "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.itd_design",                      "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.min_condenser_pressure",            "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.hr_pl_nlev",                      "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.hc_ctl1",                         "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.hc_ctl2",                         "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.hc_ctl3",                         "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.hc_ctl4",                         "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.hc_ctl5",                         "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.hc_ctl6",                         "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.hc_ctl7",                         "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.hc_ctl8",                         "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.pwrb.hc_ctl9",                         "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.storage_bypass",                   "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.dry_loss_coeff",                   "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.full_load_ts_hours",               "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.heater_eff",                       "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.hot_heater_max_load",              "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.hot_heater_set_temp",              "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.cold_heater_max_load",             "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.cold_heater_set_temp",             "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.init_cold_htf_temp",               "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.init_cold_htf_vol",                "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.init_hot_htf_temp",                "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.init_hot_htf_vol",                 "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.max_fluid_vol",                    "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.min_fluid_vol",                    "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.parallel_tank_pairs",              "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_STRING,      "csp.pt.tes.sched.weekday",                    "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_STRING,      "csp.pt.tes.sched.weekend",                    "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.storage_htf_vol",                  "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.storage_type",                     "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.tank_diameter",                    "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.tank_height",                      "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.wetted_loss_coeff",                "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp1.fossil",                     "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp1.nosolar",                    "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp1.solar",                      "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp1.turbout",                    "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp2.fossil",                     "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp2.nosolar",                    "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp2.solar",                      "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp2.turbout",                    "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp3.fossil",                     "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp3.nosolar",                    "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp3.solar",                      "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp3.turbout",                    "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp4.fossil",                     "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp4.nosolar",                    "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp4.solar",                      "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp4.turbout",                    "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp5.fossil",                     "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp5.nosolar",                    "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp5.solar",                      "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp5.turbout",                    "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp6.fossil",                     "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp6.nosolar",                    "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp6.solar",                      "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp6.turbout",                    "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp7.fossil",                     "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp7.nosolar",                    "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp7.solar",                      "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp7.turbout",                    "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp8.fossil",                     "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp8.nosolar",                    "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp8.solar",                      "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp8.turbout",                    "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp9.fossil",                     "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp9.nosolar",                    "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp9.solar",                      "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.tes.disp9.turbout",                    "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.par.heliostat_startup_energy",            "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.par.heliostat_tracking_power",            "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.par.piping_loss_coeff",                "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.par.rec_htf_pump_eff",                 "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.par.storage_pump_power",               "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.par.total_piping_length",              "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.par.aux_c0",                           "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.par.aux_c1",                           "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.par.aux_c2",                           "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.par.aux_pf",                           "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.par.aux_val",                          "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.par.bop_c0",                           "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.par.bop_c1",                           "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.par.bop_c2",                           "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.par.bop_pf",                           "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.par.bop_val",                          "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_INPUT,        SSC_NUMBER,      "csp.pt.par.pb_fixed_frac",                    "",                                                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	
	
// outputs
	{ SSC_OUTPUT,        SSC_ARRAY,       "system.hourly.dni",                           "DNI (kW/m2-hr), Hourly",                                "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_OUTPUT,        SSC_ARRAY,       "system.hourly.windspd",                       "Wind Speed (m/s), Hourly",                              "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_OUTPUT,        SSC_ARRAY,       "system.hourly.ambtemp",                       "Ambient Temp ('C), Hourly",                             "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_OUTPUT,        SSC_ARRAY,       "system.hourly.sol_rad_inc_on_col",            "Incident Solar Radiation, Hourly",                      "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_OUTPUT,        SSC_ARRAY,       "system.hourly.thermal_energy_from_sf",            "Thermal Energy From SF, Hourly",                        "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_OUTPUT,        SSC_ARRAY,       "system.hourly.thermal_energy_to_powerblock",            "Thermal Energy to Power Block, Hourly",                 "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_OUTPUT,        SSC_ARRAY,       "system.hourly.gross_electric_output",            "Gross Electric Output (kWh), Hourly",                   "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_OUTPUT,        SSC_ARRAY,       "system.hourly.e_net",                         "Net Electric Output (kWh), Hourly",                     "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_OUTPUT,        SSC_ARRAY,       "system.hourly.water_usage",                   "Water Usage (m3), Hourly",                              "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	
	{ SSC_OUTPUT,        SSC_NUMBER,      "system.annual.gross_electric_output",            "Gross Electric Output (kWh), Annual",                   "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_OUTPUT,        SSC_NUMBER,      "system.annual.e_net",                         "Net Electric Output (kWh), Annual",                     "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_OUTPUT,        SSC_NUMBER,      "system.annual.fuel_usage",                    "Annual Fuel Usage (kWht)",                              "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_OUTPUT,        SSC_NUMBER,      "system.annual.gross_to_net_conversion_factor",            "Gross to Net Conv. Factor",                             "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_OUTPUT,        SSC_NUMBER,      "system.annual.water_usage",                   "Annual Water Usage",                                    "",       "",                      "trnsys.tower",       "*",                    "",                              "" },
	{ SSC_OUTPUT,        SSC_NUMBER,      "system.annual.washing_water_usage",            "Annual Washing Water Usage (m3)",                       "",       "",                      "trnsys.tower",       "*",                    "",                              "" },

var_info_invalid };


class cm_trntower : public cm_trnbase
{
private:
public:
	cm_trntower() : cm_trnbase()
	{
		add_var_info( _cm_vtab_trntower );
	}

	virtual void write_include_file( FILE *fp ) throw( general_error )
	{
	}

	virtual void process_outputs() throw( general_error )
	{
		update("Saving data...", 99.5);
	}

	virtual const char *deck_name()
	{
		return "csp_tower";
	}
};

DEFINE_MODULE_ENTRY( trntower, "Power tower (central receiver) simulator (TRNSYS)", 1 )