name: Compare Test Time Elapsed

on:
  workflow_run:
      workflows: ["CI"]
      types: 
        - completed
env:
  DIFF_THRESHOLD: 0.10

jobs:
  build-on-mac:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-latest, macos-14-large, macos-latest]

    steps:
    - name: Get Filename
      if: ${{ matrix.os == 'windows-2019' }}
      shell: bash
      run: echo "CI_WF=SSC Windows Test Time Elapsed" >> $GITHUB_ENV

    - name: Get Filename
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: echo "CI_WF=SSC Linux Test Time Elapsed" >> $GITHUB_ENV

    - name: Get Filename
      if: ${{ matrix.os == 'macos-14-large' }}
      run: echo "CI_WF=SSC Mac Intel Shared Libraries" >> $GITHUB_ENV

    - name: Get Filename
      if: ${{ matrix.os == 'macos-latest' }}
      run: echo "CI_WF=SSC Mac Arm Shared Libraries" >> $GITHUB_ENV

    - name: Get Artifact
      uses: actions/github-script@v7
      with:
        script: |
          let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
          });
          let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
            return artifact.name == "${{env.CI_WF}}"
          })[0];
          let download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: 'zip',
          });
          const fs = require('fs');
          const path = require('path');
          const temp = '${{ runner.temp }}/artifacts';
          if (!fs.existsSync(temp)){
            fs.mkdirSync(temp);
          }
          fs.writeFileSync(path.join(temp, 'test_times.zip'), Buffer.from(download.data));

    - name: Check
      shell: bash
      run: ls ${{ runner.temp }}/artifacts

    - name: Unzip Test Times
      if: ${{ matrix.os == 'windows-2019' }}
      run: 7z x ${{ runner.temp }}/artifacts/test_times.zip

    - name: Unzip Test Times
      if: ${{ matrix.os != 'windows-2019' }}
      run: unzip ${{ runner.temp }}/artifacts/test_times.zip

    - name: Compare Test Times
      shell: bash
      run: |
        ls ${{ runner.temp }}/artifacts/test
        pip install pandas
        python ${SSCDIR}/test/compare_elapsed_time.py compare ${{ runner.temp }}/artifacts/gtest_elapsed_times.csv ${{ github.ref_name }}